core/coreobjects/include/coreobjects/property_builder.h, core/opendaq/opendaq/include/opendaq/instance.h, core/opendaq/reader/include/opendaq/sample_reader.h, core/opendaq/signal/include/opendaq/data_descriptor.h, core/opendaq/signal/include/opendaq/data_rule.h, core/opendaq/signal/include/opendaq/dimension_builder.h, core/opendaq/signal/include/opendaq/packet.h, core/opendaq/signal/include/opendaq/scaling.h, core/opendaq/signal/include/opendaq/scaling_builder.h
There are some minor issues with the in-source documentation which I tried to fix, but there needs to be additional input especially in `instance.h` where docu comment was missing for the second factory function. 
Please feel free to work on it.
=> fixing and adding some in-source documentation

bindings/python/core_objects/generated/py_property_value_event_args.cpp, bindings/python/opendaq/generated/logger/py_logger_sink.cpp, bindings/python/opendaq/generated/reader/py_reader.cpp, bindings/python/opendaq/generated/reader/py_sample_reader.cpp, bindings/python/opendaq/generated/signal/py_data_rule.cpp, bindings/python/opendaq/generated/signal/py_dimension_rule.cpp, bindings/python/opendaq/generated/signal/py_input_port_config.cpp, bindings/python/opendaq/generated/signal/py_packet.cpp, bindings/python/opendaq/generated/signal/py_scaling.cpp, bindings/python/opendaq/py_opendaq.cpp, shared/tools/RTGen/bin/Templates/python.template, shared/tools/RTGen/src/project/RTGen.Python/Templates/python.template
The motivation for this is fixing `pybind11_stubgen`, described in #21.
It is not a complete fix, but it does shorten the error list.
=> Move Python enums from definition to declaration

core/opendaq/component/src/CMakeLists.txt, core/opendaq/device/src/CMakeLists.txt
=> make folder_impl.h and io_folder_impl.h publicly available

.github/workflows/check_headers.yml, .github/workflows/ci.yml, docs/Antora/modules/getting_started/pages/quick_start_application.adoc, docs/Antora/modules/getting_started/pages/quick_start_building_opendaq.adoc, docs/Antora/modules/getting_started/pages/quick_start_setting_up_cpp.adoc, docs/Antora/modules/howto_guides/pages/howto_add_function_block.adoc, docs/Antora/modules/howto_guides/pages/howto_configure_function_block.adoc, docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
I've been working a bit through the documentation and these are some tweaks I would propose. Nice job overall, I'm especially happy that `pip install opendaq` just worked(tm) :) .
=> Documentation python example tweaks

bindings/python/core_objects/generated/py_property_object_class_builder.cpp, changelog/changelog_2.0.0-3.0.0.txt, core/coreobjects/include/coreobjects/property_object_class_builder.h, core/coreobjects/include/coreobjects/property_object_class_builder_impl.h, core/coreobjects/src/property_object_class_builder_impl.cpp
=> Replace weak reference in property_object_class builder interface

shared/libraries/opcua/opcuaclient/include/opcuaclient/attribute_reader.h, shared/libraries/opcua/opcuaclient/src/CMakeLists.txt, shared/libraries/opcua/opcuaclient/src/attribute_reader.cpp, shared/libraries/opcua/opcuaclient/tests/CMakeLists.txt, shared/libraries/opcua/opcuaclient/tests/include/opcuaservertesthelper.h, shared/libraries/opcua/opcuaclient/tests/src/opcuaservertesthelper.cpp, shared/libraries/opcua/opcuaclient/tests/src/test_attribute_reader.cpp, shared/libraries/opcua/opcuashared/include/opcuashared/opcua_attribute.h, shared/libraries/opcua/opcuashared/src/CMakeLists.txt
=> <TBBAS-1200> Implement opcua attribute reader

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/package.yml, core/opendaq/signal/src/dimension_impl.cpp
Uncommented or added Win32 to the Windows matrix and suppressed runs of pyWheel steps for this "new" platform (Win32).
=> CI - Make Win32 build available

core/coretypes/include/coretypes/arguments.h, core/coretypes/include/coretypes/intfs.h, core/coretypes/tests/test_actual_interfaces.cpp
=> Speed-up base-interface detection

.github/workflows/deploy.yml, .github/workflows/package.yml
Fixed the step-conditionals in packaging and deployment actions.
=> CI - Make Win32 build available (fixed pack and deploy scripts)

CMakeLists.txt, bindings/python/opendaq/include/py_opendaq/py_typed_reader.h, cmake/DaqUtils.cmake, core/coreobjects/include/coreobjects/property_impl.h, core/opendaq/device/include/opendaq/device_info_config.h, core/opendaq/modulemanager/src/module_manager_impl.cpp
This produces something similar to the following output:
```sh
[ModuleManager] [info] Loading modules from 'F:\openDAQ\build\bin'
[ModuleManager] [info] Loaded module [v2.0.0 Audio device module] from "audio_device_module-64-2-debug.module.dll".
[ModuleManager] [info]      DEV [miniaudio] Audio device: ""
[ModuleManager] [info]      FB  [audio_device_module_wav_writer] WAVWriter: "Writes WAV files"
[ModuleManager] [info] Loaded module [v2.0.0 Empty module] from "empty_module-64-2-debug.module.dll".
[ModuleManager] [info] Loaded module [v2.0.0 openDAQ native streaming client module] from "native_stream_cl_module-64-2-debug.module.dll".
[ModuleManager] [info]      DEV [daq.nsd] Device: "Pseudo device, provides only signals of the remote device as …
```
=> Make Module manager print loaded modules their versions and supported components

docs/Antora/modules/background_info/nav-background_info.adoc, docs/Antora/modules/background_info/pages/device.adoc, docs/Antora/modules/background_info/pages/modules.adoc, docs/Antora/modules/background_info/pages/opendaq_architecture.adoc, docs/Antora/modules/background_info/pages/streaming.adoc, docs/Antora/modules/glossary/pages/glossary.adoc, docs/Antora/modules/howto_guides/nav-howto-guides.adoc, docs/Antora/modules/howto_guides/pages/howto_configure_streaming.adoc, docs/tests/test_streaming_config.cpp, examples/cpp/streaming_configuration_example/streaming_configuration_example.cpp
* Streaming configuration how-to
* Streaming background info
=> Add Streaming-related Antora docs pages:

docs/Antora/modules/background_info/pages/modules.adoc, examples/cpp/CMakeLists.txt
=> Fix minor typo in docs and minor bug in examples/cpp/CMakeLists.txt

core/opendaq/component/include/opendaq/component_impl.h, core/opendaq/component/tests/test_component.cpp, core/opendaq/opendaq/src/instance_impl.cpp, core/opendaq/opendaq/tests/test_instance.cpp, core/opendaq/signal/tests/test_signal_container.cpp, modules/ref_device_module/tests/test_ref_device_module.cpp, modules/tests/test_opendaq_device_modules/test_device_modules.cpp
=> Add "/" prefix to global IDs

core/opendaq/reader/include/opendaq/reader_impl.h, core/opendaq/reader/include/opendaq/typed_reader.h, core/opendaq/reader/src/signal_reader.cpp, core/opendaq/reader/src/stream_reader_impl.cpp, core/opendaq/reader/src/typed_reader.cpp
=> Fix Readers detection of Signal's raw sample-type

external/native_streaming/CMakeLists.txt, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_device_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_factory.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_signal_impl.h, modules/native_streaming_client_module/src/native_streaming_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_impl.cpp, modules/native_streaming_client_module/src/native_streaming_signal_impl.cpp, modules/tests/test_opendaq_device_modules/test_helpers.h, modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp, modules/tests/test_opendaq_device_modules/test_streaming.cpp, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/client_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_client_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_protocol_types.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/server_session_handler.h, shared/libraries/native_streaming_protocol/src/base_session_handler.cpp, shared/libraries/native_streaming_protocol/src/client_session_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp, shared/libraries/native_streaming_protocol/src/server_session_handler.cpp, shared/libraries/native_streaming_protocol/tests/test_protocol.cpp
=> Auto-reconnect feature

core/opendaq/reader/include/opendaq/reader_impl.h, core/opendaq/reader/include/opendaq/typed_reader.h, core/opendaq/reader/src/signal_reader.cpp, core/opendaq/reader/src/stream_reader_impl.cpp, core/opendaq/reader/src/typed_reader.cpp, modules/ref_device_module/include/ref_device_module/ref_device_impl.h, modules/ref_device_module/src/ref_device_impl.cpp, modules/ref_device_module/src/ref_device_module_impl.cpp
=> Support adding Sub-Devices and Function-Blocks to Reference device

bindings/python/tests/test_property_system.py, core/corecontainers/include/coretypes/dictobject_impl.h, core/corecontainers/include/coretypes/listobject_impl.h, core/corecontainers/src/dictobject_impl.cpp, core/corecontainers/src/listobject_impl.cpp, core/coreobjects/include/coreobjects/property_object_impl.h, core/coreobjects/tests/test_property_object.cpp, core/coretypes/include/coretypes/cloneable.h, core/coretypes/tests/test_dictobject.cpp, core/coretypes/tests/test_listobject.cpp, docs/Antora/modules/background_info/pages/property_system.adoc, docs/tests/test_property_system.cpp, modules/native_streaming_client_module/src/CMakeLists.txt
=> Clone list/dict on property value get/set

core/coretypes/include/coretypes/type_manager.h, core/coretypes/include/coretypes/type_manager_ptr.h, core/coretypes/tests/test_type_manager.cpp, shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h, shared/libraries/config_protocol/include/config_protocol/config_protocol_server.h, shared/libraries/config_protocol/src/config_protocol_client.cpp, shared/libraries/config_protocol/src/config_protocol_server.cpp, shared/libraries/config_protocol/tests/test_config_client_server.cpp, shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
Added test for struct properties. Enum properties (when implemented) should also work.
=> Transfer type manager via native config protocol and register the types

core/coreobjects/tests/test_property_object.cpp, core/coretypes/tests/test_struct.cpp, core/opendaq/component/include/opendaq/component_impl.h, core/opendaq/component/tests/test_component.cpp, core/opendaq/device/tests/test_device.cpp, core/opendaq/device/tests/test_device_info.cpp, core/opendaq/device/tests/test_tree_traversal.cpp, core/opendaq/opendaq/tests/test_core_events.cpp, core/opendaq/opendaq/tests/test_instance.cpp, core/opendaq/reader/tests/test_multi_reader.cpp, core/opendaq/signal/tests/test_data_packet.cpp, core/opendaq/signal/tests/test_signal_container.cpp
Building issues with the VS2017. 
The missing include directive is probably compiler-related, but I don't know how your tests didn't detect signed/unsigned compare warnings.
=> Fix compile error

cmake/DaqComponents.cmake, core/opendaq/component/include/opendaq/component_impl.h, core/opendaq/context/src/CMakeLists.txt, shared/libraries/opcuatms/tests/CMakeLists.txt, shared/libraries/opcuatms/tests/opcuatms_integration/CMakeLists.txt, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_function_block.cpp, shared/libraries/websocket_streaming/src/CMakeLists.txt
=> Fix openDAQ component (static) libraries linking

external/native_streaming/CMakeLists.txt, shared/libraries/config_protocol/tests/test_config_packet.cpp
Update the native streaming library to v1.0.2 and remove some warnings
=> Update native streaming library

modules/ref_fb_module/include/ref_fb_module/trigger_fb_impl.h, modules/ref_fb_module/src/CMakeLists.txt, modules/ref_fb_module/src/ref_fb_module_impl.cpp, modules/ref_fb_module/src/trigger_fb_impl.cpp, modules/ref_fb_module/tests/CMakeLists.txt, modules/ref_fb_module/tests/test_fb_trigger.cpp, modules/ref_fb_module/tests/test_ref_fb_module.cpp
=> Add trigger function block with tests

core/opendaq/opendaq/src/json_config_provider_impl.cpp
Added missing include. Compiler: VS2017.
=> Add missing include for std::tolower

modules/ref_fb_module/include/ref_fb_module/trigger_fb_impl.h, modules/ref_fb_module/src/ref_fb_module_impl.cpp, modules/ref_fb_module/src/trigger_fb_impl.cpp, modules/ref_fb_module/tests/test_fb_trigger.cpp
=> Test trigger using SameThread and minor trigger function block changes

modules/ref_fb_module/include/ref_fb_module/trigger_fb_impl.h, modules/ref_fb_module/src/trigger_fb_impl.cpp, modules/ref_fb_module/tests/test_fb_trigger.cpp
=> A few minor stylistic changes to trigger function block

core/coreobjects/include/coreobjects/property_object_class_builder.h, core/opendaq/opendaq/tests/test_config_provider.cpp, core/opendaq/signal/tests/test_data_descriptor.cpp, docs/tests/test_architecture.cpp, docs/tests/test_examples.cpp, docs/tests/test_modules.cpp, docs/tests/test_property_system.cpp, docs/tests/test_quick_start.cpp, docs/tests/test_signals.cpp, docs/tests/test_streaming_config.cpp, external/native_streaming/CMakeLists.txt, modules/ref_device_module/tests/test_ref_device_module.cpp, modules/ref_fb_module/tests/test_fb_trigger.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp, modules/tests/test_opendaq_device_modules/test_streaming.cpp, modules/tests/test_opendaq_device_modules/test_subdevices.cpp, modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp, modules/tests/test_ref_modules/test_ref_modules.cpp, shared/libraries/config_protocol/tests/test_core_events.cpp, shared/libraries/opcuatms/opcuatms/tests/test_generic_struct_converter.cpp, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_function_property.cpp, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_integration.cpp
It would be great if we'd add a MSVC 2017 Win32 pipeline so such obvious errors are not event introduced
=> Fix Visual Studio 2017 Compilation

core/coreobjects/include/coreobjects/core_event_args.h, core/coreobjects/include/coreobjects/core_event_args_factory.h, core/coreobjects/include/coreobjects/core_event_args_impl.h, core/coreobjects/src/core_event_args_impl.cpp, core/coretypes/include/coretypes/event_handler_impl.h, core/coretypes/include/coretypes/type_manager_impl.h, core/coretypes/include/coretypes/type_manager_private.h, core/coretypes/src/CMakeLists.txt, core/coretypes/src/type_manager_impl.cpp, core/opendaq/modulemanager/src/context_impl.cpp, core/opendaq/opendaq/tests/test_core_events.cpp, shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h, shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h, shared/libraries/config_protocol/include/config_protocol/config_client_folder_impl.h, shared/libraries/config_protocol/include/config_protocol/config_client_input_port_impl.h, shared/libraries/config_protocol/include/config_protocol/config_client_signal_impl.h, shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h, shared/libraries/config_protocol/src/config_protocol_server.cpp, shared/libraries/config_protocol/tests/test_core_events.cpp
=> Add TypeAdded/Removed core event

docs/Antora/modules/howto_guides/nav-howto-guides.adoc, docs/Antora/modules/howto_guides/pages/howto_measure_single_value.adoc
I found it useful to be able to get a measurement value in a simple way and think it should be highlighted in the how_to docs
=> add howto on simple measure of single value

examples/python/gui_demo.py
Python gui_demo app refactoring
=> [TBBAS-1162] Python GUI App refactoring

core/opendaq/functionblock/include/opendaq/function_block_impl.h, docs/Antora/modules/background_info/pages/components.adoc, docs/Antora/modules/background_info/pages/function_blocks.adoc, docs/Antora/modules/background_info/pages/opendaq_architecture.adoc, docs/Antora/modules/background_info/pages/signals.adoc, docs/tests/test_components.cpp, modules/native_streaming_client_module/src/native_streaming_device_impl.cpp, modules/ref_fb_module/include/ref_fb_module/scaling_fb_impl.h, modules/ref_fb_module/src/scaling_fb_impl.cpp, modules/tests/test_ref_modules/test_ref_modules.cpp
Adds an implementation example for component statuses - input status of scaling function block
=> <TBBAS-1390> Input status of scaling function block

core/coreobjects/include/coreobjects/property_object_impl.h, core/opendaq/device/include/opendaq/device_impl.h, core/opendaq/device/include/opendaq/device_info.h, core/opendaq/device/include/opendaq/device_info_config.h, core/opendaq/device/include/opendaq/device_info_factory.h, core/opendaq/device/include/opendaq/device_info_impl.h, core/opendaq/device/src/device_info_impl.cpp, core/opendaq/device/tests/test_device_info.cpp, modules/opcua_server_module/src/opcua_server_impl.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp, shared/libraries/config_protocol/tests/test_utils.cpp, shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp, shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/tms_server.h, shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_device.cpp, shared/libraries/opcuatms/opcuatms_server/src/tms_server.cpp, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
=> Add SDK version to device info

modules/ref_fb_module/include/ref_fb_module/statistics_fb_impl.h, modules/ref_fb_module/src/statistics_fb_impl.cpp, modules/ref_fb_module/tests/test_fb_statistics.cpp, modules/ref_fb_module/tests/test_fb_trigger.cpp
- Adds a working trigger function block as a nested function block in statistics function block with tests
- Statistics uses the trigger outputs to determine when it should calculate, and when not to
- The trigger function block can be added based on a Boolean property of the statistics function block
=> Statistics nested trigger

core/opendaq/opendaq/src/instance_impl.cpp
Can check what is root device from log file.
=> Log root device selection

bindings/python/core_types/generated/py_struct.cpp, bindings/python/core_types/src/py_converter.cpp, bindings/python/tests/test_core_types.py, core/coretypes/include/coretypes/ctutils.h, core/coretypes/src/struct_type_impl.cpp, core/coretypes/src/type_manager_impl.cpp
- IStruct named values as attributes
- TypeManager type names validation
- Struct field names validation
- Tests updated
=> [TBBAS-1362] IStruct Python bindings improvements

shared/libraries/websocket_streaming/src/async_packet_reader.cpp
- [x Pull request title reflects its content
=> hiding not public signals in streaming lt 

modules/ref_device_module/include/ref_device_module/ref_channel_impl.h, modules/ref_device_module/src/ref_channel_impl.cpp, modules/ref_device_module/tests/test_ref_device_module.cpp
Required for more exact performance testing
=> Add option to reference device to set fixed packet size

.github/workflows/ci.yml, bindings/dotnet/CMakeLists.txt, bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/GlobalUsings.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/OpenDAQ_CITests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/openDAQ.Net.CI.Test.csproj, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesBaseObjectTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesBoolTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesFloatTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesIntegerTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesStringTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDAQTestsBase.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDAQ_Tests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqHowToGuidesTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqTranslatedCppTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/openDAQ.Net.Test.csproj, bindings/dotnet/openDAQ.Net/openDAQ.Net.sln, bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj, shared/tools/license-header-checker/ignore-filter.txt
There is a new Test-Project which will be run from CI using `ctest`, producing `juinit` compatible report which is copied to the other reports for archiving in GitHub Artifacts.
Also the .NET Bindings generation has been removed from all Jobs except for `Windows, VS 2022 x64, Debug+Release`.
=> [TBBAS-1381] .NET Bindings - Provide minimal tests for CI

shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_impl.cpp
=> ToDaqObject returns nullptr instead of throwing an exception.

bindings/python/core_objects/generated/py_property.cpp, bindings/python/core_objects/generated/py_property_object_class_builder.cpp, bindings/python/opendaq/generated/component/py_tags_private.cpp, bindings/python/opendaq/generated/logger/py_logger_sink.cpp, bindings/python/opendaq/generated/signal/py_connection.cpp, core/opendaq/component/include/opendaq/tags_impl.h, core/opendaq/component/include/opendaq/tags_private.h, core/opendaq/modulemanager/src/context_impl.cpp, core/opendaq/reader/include/opendaq/multi_reader.h, core/opendaq/reader/include/opendaq/multi_reader_impl.h, core/opendaq/reader/src/multi_reader_impl.cpp, core/opendaq/reader/tests/test_stream_reader.cpp, core/opendaq/server/tests/test_server_type.cpp, external/native_streaming/CMakeLists.txt, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp, shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h, shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/client_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/server_session_handler.h, shared/libraries/native_streaming_protocol/src/client_session_handler.cpp, shared/libraries/native_streaming_protocol/src/server_session_handler.cpp, shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_tags_impl.h, shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_tags_impl.cpp, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_integration.cpp, simulator/simulator_app/src/main.cpp
=> Fixes for MSVC 2017 and Delphi bindings

core/coreobjects/include/coreobjects/property_object_impl.h, core/coreobjects/tests/test_derivedpropertyobject.cpp, core/opendaq/component/tests/test_component.cpp
=> Prevent adding non-IPropertyObject default values

changelog/changelog_2.0.0-3.0.0.txt, external/native_streaming/CMakeLists.txt, modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_device_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_impl.h, modules/native_streaming_client_module/src/native_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/native_streaming_client_module/src/native_streaming_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_impl.cpp, modules/native_streaming_server_module/include/native_streaming_server_module/native_streaming_server_impl.h, modules/native_streaming_server_module/src/native_streaming_server_impl.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/client_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_client_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_protocol_types.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/server_session_handler.h, shared/libraries/native_streaming_protocol/src/base_session_handler.cpp, shared/libraries/native_streaming_protocol/src/client_session_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp, shared/libraries/native_streaming_protocol/src/server_session_handler.cpp, shared/libraries/native_streaming_protocol/tests/test_base.h, shared/libraries/native_streaming_protocol/tests/test_config_packets.cpp, shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
=> Native protocol disconnection detection optimizations

shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h, shared/libraries/config_protocol/include/config_protocol/config_server_component.h, shared/libraries/config_protocol/tests/test_config_client_server.cpp, shared/libraries/config_protocol/tests/test_core_events.cpp
=> Add config client setActive support

modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_device_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_impl.h, modules/native_streaming_client_module/src/native_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/native_streaming_client_module/src/native_streaming_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_impl.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp, shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h, shared/libraries/config_protocol/include/config_protocol/config_client_folder_impl.h, shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h, shared/libraries/config_protocol/include/config_protocol/config_protocol_server.h, shared/libraries/config_protocol/src/config_protocol_client.cpp, shared/libraries/config_protocol/src/config_protocol_server.cpp, shared/libraries/config_protocol/tests/test_core_events.cpp, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/client_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_client_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/server_session_handler.h, shared/libraries/native_streaming_protocol/src/base_session_handler.cpp, shared/libraries/native_streaming_protocol/src/client_session_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp, shared/libraries/native_streaming_protocol/src/server_session_handler.cpp, shared/libraries/native_streaming_protocol/tests/test_base.h, shared/libraries/native_streaming_protocol/tests/test_config_packets.cpp, shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
draft
TODO: enable streaming for signals added via Component update
=> Native config device reconnection

core/coretypes/tests/test_type_manager.cpp, core/opendaq/opendaq/src/client_impl.cpp, shared/libraries/discovery/include/daq_discovery/daq_discovery_client.h, shared/libraries/discovery/src/daq_discovery_client.cpp
This should fix Delphi debugger stutters
=> Run mDNS discovery synchronously as this is now handled by client device

bindings/python/core_types/CMakeLists.txt
=> Fix compiling python bindings on Windows/MSVC in Debug configuration

bindings/python/core_objects/generated/py_property.cpp, bindings/python/core_objects/generated/py_property_builder.cpp, bindings/python/opendaq/generated/signal/py_data_packet.cpp, changelog/changelog_2.0.0-3.0.0.txt, core/opendaq/device/include/opendaq/device_impl.h, core/opendaq/modulemanager/include/opendaq/module.h, core/opendaq/modulemanager/include/opendaq/module_manager_impl.h, core/opendaq/modulemanager/include/opendaq/module_manager_utils.h, core/opendaq/modulemanager/src/CMakeLists.txt, core/opendaq/modulemanager/src/module_manager_impl.cpp, core/opendaq/opendaq/include/opendaq/client_impl.h, core/opendaq/opendaq/include/opendaq/instance.h, core/opendaq/opendaq/include/opendaq/instance_factory.h, core/opendaq/opendaq/mocks/include/opendaq/mock/mock_physical_device.h, core/opendaq/opendaq/mocks/mock_device_module.cpp, core/opendaq/opendaq/mocks/mock_physical_device.cpp, core/opendaq/opendaq/src/client_impl.cpp, core/opendaq/opendaq/tests/test_instance.cpp, core/opendaq/signal/include/opendaq/signal_container_impl.h, docs/tests/test_modules.cpp, modules/ref_device_module/include/ref_device_module/ref_device_impl.h, modules/ref_device_module/src/ref_device_impl.cpp, shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/tms_client.h, shared/libraries/opcuatms/opcuatms_client/src/tms_client.cpp, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_integration.cpp
- Move create fb/device logic to module manager
- Move client device logic for adding fbs/devices to device_impl
=> Move create fb/device logic to module manager

bindings/python/opendaq/generated/modulemanager/py_module_manager.cpp, bindings/python/opendaq/generated/opendaq/py_instance_builder.cpp, bindings/python/package/opendaq/__init__.py, bindings/python/run_rtgen.sh, changelog/changelog_2.0.0-3.0.0.txt, core/opendaq/modulemanager/include/opendaq/module_manager.h, core/opendaq/modulemanager/include/opendaq/module_manager_factory.h, core/opendaq/modulemanager/include/opendaq/module_manager_impl.h, core/opendaq/modulemanager/src/module_manager_impl.cpp, core/opendaq/opendaq/include/opendaq/instance_builder.h, core/opendaq/opendaq/include/opendaq/instance_builder_impl.h, core/opendaq/opendaq/src/instance_builder_impl.cpp, core/opendaq/opendaq/src/instance_impl.cpp
Module manager now handles multiple search paths
=> [TBBAS-1299] Add support for multiple module paths in InstanceBuilder

core/coretypes/include/coretypes/struct_type_factory.h, core/opendaq/signal/include/opendaq/data_packet.h, core/opendaq/signal/include/opendaq/data_packet_impl.h, core/opendaq/signal/include/opendaq/signal.h, core/opendaq/signal/include/opendaq/signal_impl.h, core/opendaq/signal/src/data_descriptor_impl.cpp, core/opendaq/signal/tests/test_signal.cpp, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_signal.cpp
Support lists in getLastValue (including list of structs), support lists as a nested type for structs in getLastValue for core with tests (also add test for lists of simple (non-struct) values via OPC UA, which works out of the box).
=> Support lists in getLastValue

core/opendaq/reader/include/opendaq/multi_reader.h, core/opendaq/reader/include/opendaq/multi_reader_impl.h, core/opendaq/reader/src/multi_reader_impl.cpp, core/opendaq/reader/tests/test_multi_reader.cpp
=> Add getter for common sample rate, update documentation comments

core/opendaq/opendaq/mocks/include/opendaq/mock/mock_physical_device.h, core/opendaq/opendaq/mocks/mock_physical_device.cpp, core/opendaq/streaming/include/opendaq/mirrored_signal_impl.h, modules/native_streaming_client_module/src/native_streaming_signal_impl.cpp, modules/tests/test_opendaq_device_modules/test_helpers.h, modules/tests/test_opendaq_device_modules/test_streaming.cpp, shared/libraries/config_protocol/include/config_protocol/config_client_signal_impl.h, shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_signal_impl.h, shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_signal_impl.cpp, shared/libraries/signal_generator/src/signal_generator.cpp, shared/libraries/websocket_streaming/src/websocket_client_signal_impl.cpp, shared/libraries/websocket_streaming/tests/test_signal_generator.cpp
=> Reset mirrored descriptor on unsubscribe

core/opendaq/opendaq/src/instance_impl.cpp
=> Fix annoying and unspecific "Not Found" error on device startup

core/opendaq/device/tests/test_device_info.cpp, core/opendaq/reader/tests/test_multi_reader.cpp, core/opendaq/signal/tests/test_data_packet.cpp, core/opendaq/signal/tests/test_signal.cpp, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
=> Fix MSVC Win32 build

core/opendaq/device/include/opendaq/server_capability.h, core/opendaq/device/include/opendaq/server_capability_config.h
=> Fix `server_capability.h` and `server_capability_config.h` bindings

core/opendaq/reader/include/opendaq/block_reader_impl.h, core/opendaq/reader/src/block_reader_impl.cpp, external/CMakeLists.txt, external/kissfft/CMakeLists.txt, external/kissfft/_kiss_fft_guts.h, external/kissfft/kiss_fft.c, external/kissfft/kiss_fft.h, external/kissfft/kiss_fft_log.h, modules/ref_fb_module/include/ref_fb_module/fft_fb_impl.h, modules/ref_fb_module/src/CMakeLists.txt, modules/ref_fb_module/src/fft_fb_impl.cpp, modules/ref_fb_module/src/ref_fb_module_impl.cpp, modules/ref_fb_module/tests/test_ref_fb_module.cpp, modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
- Adds a simple reference FFT implementation
- Fixes block reader `readPackets` call
=> Add simple FFT function block + fix block reader

docs/tests/test_quick_start.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/opcua_client_module/src/opcua_client_module_impl.cpp, modules/websocket_streaming_client_module/include/websocket_streaming_client_module/websocket_streaming_client_module_impl.h, modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp, modules/websocket_streaming_client_module/tests/test_websocket_streaming_client_module.cpp, shared/libraries/discovery/include/daq_discovery/daq_discovery_client.h, shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h, shared/libraries/discovery/src/daq_discovery_client.cpp, shared/libraries/websocket_streaming/tests/test_streaming.cpp
=> [Bug]: websocket mdns discovery backward competitivity

core/opendaq/device/include/opendaq/server_capability.h, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/opcua_client_module/src/opcua_client_module_impl.cpp, modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp, shared/libraries/opcuatms/opcuatms_server/src/tms_server.cpp
=> rename server capability protocol type

core/opendaq/signal/include/opendaq/data_packet_impl.h, core/opendaq/signal/include/opendaq/packet_factory.h, core/opendaq/signal/tests/test_data_packet.cpp, external/streaming_protocol/CMakeLists.txt, modules/tests/test_ws_siggen_integration/siggen_config.json, modules/tests/test_ws_siggen_integration/test_websocket_siggen.cpp, shared/libraries/websocket_streaming/include/websocket_streaming/input_signal.h, shared/libraries/websocket_streaming/include/websocket_streaming/output_signal.h, shared/libraries/websocket_streaming/include/websocket_streaming/signal_descriptor_converter.h, shared/libraries/websocket_streaming/include/websocket_streaming/streaming_client.h, shared/libraries/websocket_streaming/include/websocket_streaming/streaming_server.h, shared/libraries/websocket_streaming/include/websocket_streaming/websocket_client_device_impl.h, shared/libraries/websocket_streaming/include/websocket_streaming/websocket_client_signal_impl.h, shared/libraries/websocket_streaming/include/websocket_streaming/websocket_streaming.h, shared/libraries/websocket_streaming/include/websocket_streaming/websocket_streaming_impl.h, shared/libraries/websocket_streaming/src/input_signal.cpp, shared/libraries/websocket_streaming/src/output_signal.cpp, shared/libraries/websocket_streaming/src/signal_descriptor_converter.cpp, shared/libraries/websocket_streaming/src/streaming_client.cpp, shared/libraries/websocket_streaming/src/streaming_server.cpp, shared/libraries/websocket_streaming/src/websocket_client_device_impl.cpp, shared/libraries/websocket_streaming/src/websocket_client_signal_impl.cpp, shared/libraries/websocket_streaming/src/websocket_streaming_impl.cpp, shared/libraries/websocket_streaming/tests/streaming_test_helpers.h, shared/libraries/websocket_streaming/tests/test_signal_descriptor_converter.cpp, shared/libraries/websocket_streaming/tests/test_streaming.cpp, shared/libraries/websocket_streaming/tests/test_websocket_client_device.cpp
=> Streaming-lt constant rule signal integration

core/opendaq/modulemanager/include/opendaq/context_factory.h, core/opendaq/signal/include/opendaq/packet_factory.h, core/opendaq/signal/tests/test_data_packet.cpp
* Introduce a failing test that throws on getLastValue call
* Introduce fix for the test
* Fix NullContext comment
=> Last value pragma fix

antora-playbook-dev.yml, antora-playbook.yml
Update ui-bundle version from antora-ui-spring release 1.1 to 1.2 (thereby fixing the Antora docs link in the header)
=> Update ui-bundle version (Antora)

bindings/python/package/METADATA.in
PIP METADATA: Update Development Status classifier to Production/Stable
=> Update PIP package metadata

core/opendaq/opendaq/mocks/include/opendaq/gmock/streaming.h, core/opendaq/opendaq/tests/test_instance.cpp, core/opendaq/signal/include/opendaq/signal_impl.h, core/opendaq/streaming/include/opendaq/mirrored_signal_impl.h, core/opendaq/streaming/include/opendaq/mirrored_signal_private.h, modules/tests/test_ref_modules/test_ref_modules.cpp, shared/libraries/config_protocol/include/config_protocol/config_client_signal_impl.h, shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h, shared/libraries/config_protocol/include/config_protocol/config_server_signal.h, shared/libraries/config_protocol/src/CMakeLists.txt, shared/libraries/config_protocol/src/config_protocol_client.cpp, shared/libraries/config_protocol/src/config_protocol_server.cpp, shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp, shared/libraries/config_protocol/tests/test_utils.cpp
=> Add getLastValue support over native when no streaming is available

app/audio_application/CMakeLists.txt, core/coreobjects/src/CMakeLists.txt, core/coreobjects/src/authentication_provider_impl.cpp, core/coretypes/include/coretypes/filesystem.h, core/coretypes/src/CMakeLists.txt, core/opendaq/modulemanager/include/opendaq/boost_dll.h, core/opendaq/opendaq/src/json_config_provider_impl.cpp, shared/libraries/config_protocol/CMakeLists.txt
=> Fix Filesystem library use so it works on all platforms

changelog/changelog_3.0.0-4.0.0.txt, core/coreobjects/include/coreobjects/permissions.h, core/coreobjects/include/coreobjects/permissions_builder.h, core/coreobjects/include/coreobjects/permissions_builder_impl.h, core/coreobjects/src/permissions_builder_impl.cpp, core/coreobjects/tests/test_permission_manager.cpp, core/coreobjects/tests/test_permissions_builder.cpp, core/opendaq/component/include/opendaq/component_impl.h, core/opendaq/opendaq/tests/test_access_control.cpp
=> Change `IPermissions` and `IPermissionsBuilder` to fix Delphi bindings

.github/workflows/check_headers.yml, shared/tools/license-header-checker/ignore-filter.txt
I added 2 files to the header-check exclusion list which obviously come from external sources.
Also the action now gives a hint on failure how to fix license header issues.
=> Fixed license header error for 2 ping library files (exclusions) and give fixing hint in check_headers.yml

.github/workflows/check_headers.yml, .github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/package.yml, .github/workflows/reusable_nuget_creation_and_test.yml, bindings/dotnet/CMakeLists.txt, bindings/dotnet/openDAQ.Net/openDAQ.Net.NuGet.Test/.nuget/NuGet.Config, bindings/dotnet/openDAQ.Net/openDAQ.Net.NuGet.Test/openDAQ.Net.NuGet.Test.csproj, bindings/dotnet/openDAQ.Net/openDAQ.Net.sln, bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj, bindings/dotnet/openDAQ.Net/openDAQ_Net-RTGen.sln, shared/tools/license-header-checker/ignore-filter.txt
Now the .NET Bindings NuGet package is created and tested in separate jobs, implemented as "reusable workflow" (`reusable_nuget_creation_and_test.yml`).
There are no special yaml testing conditions inside, it's in a mergeable state. Though I'm not so sure about ci workflow for release branches.
=> [TBBAS-1364]&[TBBAS-1124] .NET Bindings - Generate NuGet package and test it

core/opendaq/component/src/search_filter_impl.cpp, core/opendaq/component/tests/CMakeLists.txt, core/opendaq/component/tests/test_search_filter.cpp
Pullrequest fixes the RequireTags filter and adds unit tests.
=> Fix require tags filter

modules/ref_fb_module/include/ref_fb_module/classifier_fb_impl.h, modules/ref_fb_module/src/classifier_fb_impl.cpp, modules/tests/test_ref_modules/test_ref_modules.cpp
=> Simplify classifier fb

examples/python/gui_demo.py
=> Fix crash in python GUI when setting float selection property

docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
=> refactor connection doc 

bindings/python/package/opendaq/__init__.py
Logger parameter removed in Instance constructor in Python bindings, so default one is created implicitly
=> Python: Logger removed in Instance constructor 

core/opendaq/reader/src/stream_reader_impl.cpp, docs/Antora/modules/background_info/pages/device.adoc, docs/Antora/modules/background_info/pages/modules.adoc, docs/Antora/modules/background_info/pages/property_system.adoc, docs/Antora/modules/background_info/pages/streaming.adoc, docs/Antora/modules/getting_started/pages/quick_start_application.adoc, docs/Antora/modules/glossary/pages/glossary.adoc, docs/Antora/modules/howto_guides/pages/howto_configure_instance.adoc, docs/Antora/modules/howto_guides/pages/howto_configure_streaming.adoc, docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc, docs/Antora/modules/howto_guides/pages/howto_read_last_n_samples.adoc, docs/Antora/modules/howto_guides/pages/howto_read_with_domain.adoc, examples/cpp/client_discovery/client_discovery.cpp, examples/cpp/client_local/client_local.cpp, examples/cpp/streaming_configuration_example/streaming_configuration_example.cpp, examples/python/gui_demo.py, shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
=> Merge release 3.0 changings  to the main

external/boost/CMakeLists.txt
=> Allow overriding required Boost component libraries when building source Boost

bindings/python/core_objects/generated/py_component_type.cpp, changelog/changelog_3.0.0-4.0.0.txt, core/coreobjects/include/coreobjects/component_type.h, core/coreobjects/include/coreobjects/component_type_impl.h, core/opendaq/device/include/opendaq/device_type.h, core/opendaq/device/include/opendaq/device_type_factory.h, core/opendaq/device/include/opendaq/device_type_impl.h, core/opendaq/device/src/device_type_impl.cpp, core/opendaq/functionblock/include/opendaq/function_block_type.h, core/opendaq/functionblock/include/opendaq/function_block_type_factory.h, core/opendaq/functionblock/include/opendaq/function_block_type_impl.h, core/opendaq/functionblock/src/function_block_type_impl.cpp, core/opendaq/functionblock/tests/test_function_block.cpp, core/opendaq/opendaq/mocks/mock_device_module.cpp, core/opendaq/opendaq/mocks/mock_fb_module.cpp, core/opendaq/server/include/opendaq/server_type.h, core/opendaq/server/include/opendaq/server_type_factory.h, core/opendaq/server/include/opendaq/server_type_impl.h, core/opendaq/server/src/server_type_impl.cpp, core/opendaq/server/tests/test_server_type.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/native_streaming_server_module/src/native_streaming_server_impl.cpp, modules/opcua_server_module/src/opcua_server_impl.cpp, modules/ref_fb_module/src/statistics_fb_impl.cpp, modules/ref_fb_module/src/trigger_fb_impl.cpp, modules/websocket_streaming_server_module/src/websocket_streaming_server_impl.cpp, shared/libraries/config_protocol/tests/test_config_client_server.cpp, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_function_block_type.cpp, shared/libraries/testutils/src/test_comparators.cpp
=> Clone property object to create default config from type

shared/libraries/websocket_streaming/include/websocket_streaming/output_signal.h, shared/libraries/websocket_streaming/src/output_signal.cpp, shared/libraries/websocket_streaming/tests/test_websocket_client_device.cpp
=> Fix streaming-lt compatibility issues

external/streaming_protocol/CMakeLists.txt, shared/libraries/websocket_streaming/include/websocket_streaming/output_signal.h, shared/libraries/websocket_streaming/src/output_signal.cpp, shared/libraries/websocket_streaming/tests/test_websocket_client_device.cpp
The streaming protocol LT got a clean release.
=> Increase version for streaming protocol.

external/streaming_protocol/CMakeLists.txt, shared/libraries/opcua/opcuaserver/include/opcuaserver/opcuaaddnodeparams.h, shared/libraries/opcua/opcuaserver/include/opcuaserver/opcuaserver.h, shared/libraries/opcua/opcuaserver/src/opcuaaddnodeparams.cpp, shared/libraries/opcua/opcuaserver/src/opcuaserver.cpp, shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property_object.cpp, shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_variable.cpp, shared/libraries/websocket_streaming/include/websocket_streaming/output_signal.h, shared/libraries/websocket_streaming/src/output_signal.cpp, shared/libraries/websocket_streaming/src/signal_descriptor_converter.cpp, shared/libraries/websocket_streaming/tests/test_signal_descriptor_converter.cpp, shared/libraries/websocket_streaming/tests/test_websocket_client_device.cpp
Opc-UA nodeIds as String + Version Increase of Streaming Protocol Lt to a release tag.
=>  OPC-UA NodeId clean up and streaming protocol LT uses releases tag

shared/libraries/native_streaming_protocol/src/base_session_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
=> Fix native protocol inactivity timeout handling

core/opendaq/device/include/opendaq/device_impl.h, core/opendaq/device/include/opendaq/device_info.h, core/opendaq/device/include/opendaq/device_info_config.h, core/opendaq/device/include/opendaq/device_info_impl.h, core/opendaq/device/include/opendaq/server_capability.h, core/opendaq/device/src/device_info_impl.cpp, core/opendaq/device/tests/test_device.cpp, core/opendaq/device/tests/test_device_info.cpp, core/opendaq/opendaq/mocks/mock_physical_device.cpp, core/opendaq/opendaq/tests/test_instance.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/native_streaming_client_module/src/native_streaming_device_impl.cpp, modules/opcua_client_module/src/opcua_client_module_impl.cpp, modules/ref_device_module/src/ref_device_module_impl.cpp, modules/tests/test_opendaq_device_modules/test_streaming.cpp, modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp, shared/libraries/config_protocol/include/config_protocol/config_client_folder_impl.h, shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp, shared/libraries/config_protocol/tests/test_utils.cpp, shared/libraries/config_protocol/tests/test_utils.h, shared/libraries/discovery/src/daq_discovery_client.cpp, shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp, shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp, shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp, shared/libraries/websocket_streaming/src/websocket_client_device_impl.cpp
=> Sync device name and location with device info

shared/libraries/native_streaming_protocol/src/base_session_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
=> Fix native protocol inactivity timeout handling - release patch

.github/workflows/deploy.yml
Fixed Powershell script if-statement (have to use `-ne` instead of `!=`).
=> Fixed regression in `deploy.yml`

.github/workflows/deploy.yml, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDAQ_Tests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqGettingStartedGuidesTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqHowToGuidesTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net/core/opendaq/OpenDAQFactory.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net/core/opendaq/enums/SampleType.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net/core/opendaq/reader/OpenDAQFactory.cs, docs/Antora/modules/getting_started/pages/quick_start_application.adoc, docs/Antora/modules/howto_guides/pages/howto_add_function_block.adoc, docs/Antora/modules/howto_guides/pages/howto_configure_function_block.adoc, docs/Antora/modules/howto_guides/pages/howto_configure_instance.adoc, docs/Antora/modules/howto_guides/pages/howto_configure_instance_providers.adoc, docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc, docs/Antora/modules/howto_guides/pages/howto_measure_single_value.adoc, docs/Antora/modules/howto_guides/pages/howto_read_last_n_samples.adoc, docs/Antora/modules/howto_guides/pages/howto_read_with_domain.adoc, docs/Antora/modules/howto_guides/pages/howto_read_with_timeouts.adoc, docs/Antora/modules/howto_guides/pages/howto_read_with_timestamps.adoc
Added and reworked C# examples in documentation. Some areas have been omitted due to missing functional support in .NET (yet).
=> [TBBAS-1424] Adapted and completed Antora docs with C# examples

bindings/python/opendaq/generated/device/py_device_info.cpp, changelog/changelog_3.0.0-4.0.0.txt, core/opendaq/device/include/opendaq/device_info.h, core/opendaq/device/include/opendaq/device_info_impl.h, core/opendaq/device/include/opendaq/server_capability.h, core/opendaq/device/include/opendaq/server_capability_config.h, core/opendaq/device/include/opendaq/server_capability_impl.h, core/opendaq/device/src/device_info_impl.cpp, core/opendaq/device/src/server_capability_impl.cpp, core/opendaq/device/tests/test_device_info.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/native_streaming_client_module/tests/test_native_streaming_client_module.cpp, modules/native_streaming_server_module/src/native_streaming_server_impl.cpp, modules/opcua_client_module/src/opcua_client_module_impl.cpp, modules/opcua_client_module/tests/test_opcua_client_module.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp, modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp, modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp, modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp, modules/websocket_streaming_client_module/tests/test_websocket_streaming_client_module.cpp, shared/libraries/opcuatms/opcuatms_server/src/tms_server.cpp, shared/libraries/websocket_streaming/src/websocket_streaming_server.cpp
=> Add client connection configuration info in the device info

examples/python/gui_demo.py, examples/python/gui_demo/app_context.py, examples/python/gui_demo/components/add_function_block_dialog.py, examples/python/gui_demo/components/attributes_dialog.py, examples/python/gui_demo/components/input_port_row_view.py, examples/python/gui_demo/components/output_signal_row.py, examples/python/gui_demo/utils.py
=> Python GUI app: bugfixes

core/opendaq/component/include/opendaq/component_impl.h
Warning message displays if component's local id contains whitespaces
=> Component Local ID validation

.github/workflows/ci.yml, CMakeLists.txt
=> Maintain MSVC binary compatibility with older runtime environments

antora-playbook-dev.yml, antora-playbook.yml
Fix font-weight, so it is the same in both dark and light mode - this way the text will stay in place when switching modes in Antora docs
=> Bump version of `antora-ui-spring`

docs/Antora/modules/getting_started/pages/quick_start_application.adoc, docs/Antora/modules/getting_started/pages/quick_start_setting_up_cpp.adoc, docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc, examples/cpp/quick_start/quick_start_full.cpp, examples/cpp/quick_start/quick_start_simulator.cpp, examples/python/guide/quick_start_application.py, examples/python/guide/simulator.py, modules/ref_device_module/include/ref_device_module/ref_device_impl.h, modules/ref_device_module/src/ref_device_impl.cpp, modules/ref_device_module/src/ref_device_module_impl.cpp
- Reduce quick start guide complexity
- Slight modifications to reference device module to facilitate guide
=> Quick start guide update

core/coretypes/bindings/delphi/OpenDAQ.CoreTypes.pas, core/coretypes/bindings/delphi/OpenDAQ.Deserializer.pas, core/coretypes/bindings/delphi/OpenDAQ.Exceptions.pas, core/coretypes/bindings/delphi/OpenDAQ.FunctionImpl.pas, core/coretypes/bindings/delphi/OpenDAQ.Number.pas, core/coretypes/bindings/delphi/OpenDAQ.ObjectPtr.pas, core/coretypes/bindings/delphi/OpenDAQ.ProcedureImpl.pas, core/coretypes/bindings/delphi/OpenDAQ.ProxyValue.pas, core/coretypes/bindings/delphi/OpenDAQ.SerializedList.pas, core/coretypes/bindings/delphi/OpenDAQ.SerializedObject.pas, core/coretypes/bindings/delphi/OpenDAQ.Serializer.pas, core/coretypes/bindings/delphi/OpenDAQ.TSampleType.pas, core/coretypes/bindings/delphi/OpenDAQ.TString.pas, core/coretypes/bindings/delphi/OpenDAQ.Updatable.pas, core/coretypes/bindings/delphi/OpenDAQ.VersionInfo.pas
=> Update CoreTypes Delphi bindings

core/opendaq/reader/tests/test_block_reader.cpp, core/opendaq/reader/tests/test_multi_reader.cpp, modules/tests/test_opendaq_device_modules/test_default_config.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
=> Fix MSVC 2017 Win32 compilation

core/opendaq/device/include/opendaq/device_type.h, core/opendaq/device/include/opendaq/device_type_impl.h, core/opendaq/streaming/include/opendaq/streaming_type.h, core/opendaq/streaming/include/opendaq/streaming_type_impl.h
=> Fix IDeviceType interface method calling convention

core/opendaq/opendaq/tests/test_config_provider.h, modules/ref_device_module/include/ref_device_module/common.h, modules/ref_device_module/include/ref_device_module/ref_device_impl.h, modules/ref_device_module/src/ref_device_impl.cpp, modules/ref_device_module/src/ref_device_module_impl.cpp, modules/ref_device_module/tests/test_ref_device_module.cpp, modules/tests/test_ref_modules/test_ref_modules.cpp, simulator/configurator.py, simulator/opendaq-config.json
=> Make ref device options parsing consistent

modules/native_streaming_server_module/src/native_streaming_server_impl.cpp, shared/libraries/config_protocol/include/config_protocol/config_protocol_server.h, shared/libraries/config_protocol/src/config_protocol_server.cpp, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/client_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_client_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/server_session_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h, shared/libraries/native_streaming_protocol/src/base_session_handler.cpp, shared/libraries/native_streaming_protocol/src/client_session_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp, shared/libraries/native_streaming_protocol/src/server_session_handler.cpp, shared/libraries/native_streaming_protocol/tests/CMakeLists.txt, shared/libraries/native_streaming_protocol/tests/test_client_to_dev_streaming.cpp, shared/libraries/native_streaming_protocol/tests/test_config_packets.cpp, shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
* enable transmission of streaming packets in both directions from server to client and from client to server
=> <TBBAS-1007> Enable client-to-device streaming on transport layer:

examples/python/signal_graphed_overtime.py
The example:
- selects device
- selects signal
- measures for 10 seconds
- plots the signal
- calculates some statistics (min, max, ave, rms).
The example shows how to process data collected with openDAQ in python using numpy and matlibplot.
=> Add python example

bindings/python/opendaq/include/py_opendaq/py_typed_reader.h, bindings/python/tests/test_reader_datetime.py
Python Readers return ReadStatus alongside data now
=> [TBBAS-1564] Python bindings: Readers' ReadStatuses

examples/python/gui_demo.py, examples/python/gui_demo/components/add_function_block_dialog.py, examples/python/gui_demo/components/attributes_dialog.py, examples/python/gui_demo/components/properties_view.py
Add copy/paste option to Python gui_demo:
-Copy/paste added to properties
-Copy added to attributes
-Copy added to device_info
=> Add copy/paste option to Python gui_demo 

external/native_streaming/CMakeLists.txt, modules/native_streaming_server_module/include/native_streaming_server_module/native_streaming_server_impl.h, modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
=> Fix native server shutdown process

shared/libraries/websocket_streaming/include/websocket_streaming/streaming_server.h, shared/libraries/websocket_streaming/src/streaming_server.cpp, shared/libraries/websocket_streaming/tests/test_streaming.cpp
=> Add client disconnection handling by LT-server

shared/libraries/websocket_streaming/include/websocket_streaming/streaming_server.h, shared/libraries/websocket_streaming/src/streaming_server.cpp, shared/libraries/websocket_streaming/tests/test_streaming.cpp
=> Handle client disconnection on the LT-streaming server

examples/python/gui_demo.py, examples/python/gui_demo/app_context.py, examples/python/gui_demo/components/block_view.py
Application can display custom components of the device in full topology view mode
=> [TBBAS-1717] Python GUI App: displaying custom components in full topology view

bindings/python/opendaq/generated/reader/py_stream_reader.cpp, core/opendaq/reader/include/opendaq/stream_reader.h, core/opendaq/reader/include/opendaq/stream_reader_impl.h, core/opendaq/reader/src/stream_reader_impl.cpp, core/opendaq/reader/tests/test_stream_reader.cpp
=> Fix stream reader raw data read and add skip samples method

examples/python/gui_demo/app_context.py
Short ID generating algo reworked. Long ID could be used in case of collisions
=> [TBBAS-1716] Python GUI App: short_id generating bugfix

modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h, shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp, shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
* cache the data descriptor of signal from event packet only if it is assigned
* fix race condition on signal subscribe
=> Fix event packet caching in native streaming:

.github/workflows/deploy.yml, .github/workflows/package.yml, cmake/Packing.cmake
=> Add configuration matrix for arm64

.github/workflows/deploy.yml
=> Fix deploy step

bindings/python/opendaq/generated/reader/py_block_reader.cpp, bindings/python/opendaq/generated/reader/py_multi_reader.cpp, bindings/python/opendaq/generated/reader/py_stream_reader.cpp, bindings/python/opendaq/generated/reader/py_tail_reader.cpp, bindings/python/opendaq/generated/reader/py_time_reader.cpp, bindings/python/opendaq/include/py_opendaq/py_typed_reader.h, bindings/python/tests/test_reader_datetime.py
Readers return status only if requested
=> [TBBAS-1724] ReaderStatus acquiring interface updated

modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
=> Fix native transport layer properties config parsing

bindings/python/opendaq/generated/reader/py_multi_reader.cpp, bindings/python/opendaq/generated/reader/py_stream_reader.cpp, bindings/python/tests/test_reader_datetime.py
Fix segfault in readers on call method `skip_samples` with `return_status=True`
=> Python bindings: Fix segfault in readers

core/opendaq/reader/src/multi_reader_impl.cpp
Duplicate from release 3.2 branch
=> Fix multi reader crashing due to race condition

CMakeLists.txt
Fixes https://github.com/openDAQ/openDAQ/issues/229
=> Create and install openDAQ config version cmake

modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_client_module_impl.h, modules/native_streaming_client_module/src/native_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
=> Make the native config protocol request timeout adjustable (backport)

core/opendaq/reader/tests/test_multi_reader.cpp
=> Fixing flaky multireader test in ci

bindings/python/core_types/src/py_function.cpp, examples/python/gui_demo/components/function_dialog.py, examples/python/gui_demo/components/properties_view.py, modules/ref_device_module/include/ref_device_module/ref_channel_impl.h, modules/ref_device_module/src/ref_channel_impl.cpp
Python GUI App can now execute Function properties with user-defined parameters and acquire the result of execution
=> [TBBAS-1731] Python GUI App: support executing Function-type properties

shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h, shared/libraries/config_protocol/src/config_protocol_client.cpp
=> Fix multi threaded Config protocol RPC

examples/python/gui_demo/components/attributes_dialog.py
added signal domain descriptor view and show parameters in signal domain descriptor view
=> show domain descriptor, show dictionary in descriptor view

shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp, shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
=> Fix opcua warnings

examples/python/gui_demo/app_context.py, examples/python/gui_demo/components/add_device_dialog.py, examples/python/gui_demo/components/diaolog.py
This is updated PR from forked repo. It includes some small updates. Original PR will be closed
* Adds device configuration option to "add device" window
=> Add device configuration dialog to python GUI demo

cmake/openDAQConfig.cmake.in, external/open62541/CMakeLists.txt
Correct target_name for open lib.
Correct spdlog dependency.
=> Fix: Build dependencies via find_package()

bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmInputDialog.cs, bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmMain.cs
Added functionality to save and load configuration.
Added functionality to show `SyncComponent`.
Fixed issue with empty `SelectionValues` but given value index of `0`.
P.S.: Draft as this is based on PR #451
=> [TBBAS-1358] .NET Bindings - GUI demo can save and load configuration file

bindings/python/opendaq/generated/reader/py_block_reader.cpp, bindings/python/opendaq/generated/reader/py_multi_reader.cpp, bindings/python/opendaq/generated/reader/py_stream_reader.cpp, bindings/python/opendaq/generated/reader/py_tail_reader.cpp, bindings/python/opendaq/include/py_opendaq/py_typed_reader.h, bindings/python/opendaq/py_opendaq.cpp, bindings/python/tests/test_reader_datetime.py, changelog/changelog_3.0.0-4.0.0.txt, core/opendaq/reader/include/opendaq/block_reader_impl.h, core/opendaq/reader/src/block_reader_impl.cpp, core/opendaq/reader/src/multi_reader_impl.cpp, core/opendaq/reader/src/stream_reader_impl.cpp, core/opendaq/reader/src/tail_reader_impl.cpp, core/opendaq/reader/tests/test_block_reader.cpp, core/opendaq/reader/tests/test_multi_reader.cpp, core/opendaq/reader/tests/test_stream_reader.cpp, core/opendaq/reader/tests/test_tail_reader.cpp
Python implementation added for undefined type readers
=> [TBBAS-1565] Python bindings: Undefined type readers

modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h, modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_impl.h, modules/native_streaming_client_module/src/native_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/native_streaming_client_module/src/native_streaming_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_impl.cpp, modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
=> <TBBAS-1697> Fix native streaming data processing callbacks:

core/opendaq/server/src/CMakeLists.txt
Prevents manually copying the header.
Should also be back-ported to version `3.2`.
Tested by running `cpack -C Release -G NSIS` and checking the files after using the installer.
=> Make `server_impl.h` public

examples/python/enable_device_monitoring.py
Adds example how to enable device monitoring for reconnection on native configuration & streaming
=> Add python example to enable native device & streaming monitoring

core/opendaq/server/include/opendaq/server_impl.h, examples/python/gui_demo.py, shared/libraries/config_protocol/include/config_protocol/config_client_server_impl.h, shared/libraries/config_protocol/tests/test_core_events.cpp
=> Fix unassigned parent for mirrored server component

modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h, modules/native_streaming_client_module/src/native_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h, shared/libraries/config_protocol/src/config_protocol_client.cpp
=> Native device improvements backport to release 3.2

modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h, modules/native_streaming_client_module/src/native_device_impl.cpp, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h, shared/libraries/config_protocol/src/config_protocol_client.cpp
=> Native device improvements backport to release 3.3

docs/Antora/modules/howto_guides/pages/howto_access_control.adoc
Proposes changes to the access control how-to guide.
=> Proof read access control howto guide

shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_client_handler.h, shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h, shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp, shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp, shared/libraries/native_streaming_protocol/src/server_session_handler.cpp
=> Fix native callbacks this capturing

docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
Fix a minor typo in `docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc`
=> Fix a minor typo in Antora docs

bindings/python/core_types/include/py_core_types/py_converter.h, bindings/python/opendaq/generated/signal/py_mock_signal.cpp, bindings/python/opendaq/include/py_opendaq/py_mock_signal.h, bindings/python/opendaq/include/py_opendaq/py_reader_traits.h, bindings/python/opendaq/include/py_opendaq/py_typed_reader.h, bindings/python/tests/test_packet.py, bindings/python/tests/test_reader_datetime.py, examples/python/guide/read_can_channel.py
Python readers output **Struct** typed samples as **NumPy Structured Arrays**
=> [TBBAS-1732] Python: Readers structs support

bindings/python/opendaq/generated/reader/py_multi_reader.cpp, changelog/changelog_3.0.0-4.0.0.txt, core/opendaq/reader/include/opendaq/multi_reader.h, core/opendaq/reader/include/opendaq/multi_reader_impl.h, core/opendaq/reader/include/opendaq/signal_reader.h, core/opendaq/reader/src/multi_reader_impl.cpp, core/opendaq/reader/src/signal_reader.cpp, core/opendaq/reader/tests/reader_common.h, core/opendaq/reader/tests/test_multi_reader.cpp, core/opendaq/signal/include/opendaq/signal_impl.h, modules/ref_fb_module/src/power_reader_fb_impl.cpp, modules/ref_fb_module/src/scaling_fb_impl.cpp, modules/ref_fb_module/tests/test_fb_power_reader.cpp, modules/tests/test_ref_modules/test_ref_modules.cpp
=> Option to manually invalidate reader to drop packets

modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
=> Fix native device processing threads terminating on connection exception

examples/python/gui_demo.py, examples/python/gui_demo/app_context.py, examples/python/gui_demo/components/add_config_dialog.py, examples/python/gui_demo/components/add_device_dialog.py, examples/python/gui_demo/components/add_function_block_dialog.py, examples/python/gui_demo/components/attributes_dialog.py, examples/python/gui_demo/components/block_view.py, examples/python/gui_demo/components/dialog.py, examples/python/gui_demo/components/input_port_row_view.py, examples/python/gui_demo/components/load_instance_config_dialog.py, examples/python/gui_demo/components/output_signal_row.py, examples/python/gui_demo/components/properties_view.py
IO folders displaying issues fixed
Various layout improvements
=> [TBBAS-1812][TBBAS-1817] Python GUI improvements

core/opendaq/signal/include/opendaq/data_descriptor.h
=> Add Reference Domain Info description to Data Descriptor Doxygen brief

examples/python/gui_demo.py
Temporary fix for python GUI lock errors
=> Handle python GUI lock errors

.github/ISSUE_TEMPLATE/1-BUG-REPORT.yml, .github/ISSUE_TEMPLATE/2-FEATURE-REQUEST.yml, .github/ISSUE_TEMPLATE/3-QUESTION.yml, .github/ISSUE_TEMPLATE/config.yml
Add issue templates for bugs, feature requests, and questions (with configuration)
=> Add GitHub issue templates

bindings/dotnet/openDAQ.Net/openDAQDemo.Net/openDAQDemo.Net.csproj, core/opendaq/device/include/opendaq/device_type_factory.h, core/opendaq/device/include/opendaq/device_type_impl.h, core/opendaq/device/src/device_type_impl.cpp, core/opendaq/signal/include/opendaq/input_port_impl.h, core/opendaq/signal/tests/test_data_path.cpp, core/opendaq/signal/tests/test_input_port.cpp, core/opendaq/signal/tests/test_packet_e2e.cpp, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp, regression/tests/reg_p_test_device.cpp, regression/tests/reg_p_test_input_port.cpp, shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h, shared/libraries/config_protocol/include/config_protocol/config_client_folder_impl.h, shared/libraries/config_protocol/include/config_protocol/config_client_input_port_impl.h, shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h, shared/libraries/config_protocol/include/config_protocol/config_protocol_server.h, shared/libraries/config_protocol/include/config_protocol/config_server_device.h, shared/libraries/config_protocol/include/config_protocol/config_server_input_port.h, shared/libraries/config_protocol/src/config_protocol_client.cpp, shared/libraries/config_protocol/src/config_protocol_server.cpp, shared/libraries/config_protocol/tests/test_config_client_server.cpp, shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp, shared/libraries/config_protocol/tests/test_utils.cpp, shared/libraries/config_protocol/tests/test_utils.h
Add missing remote procedure calls for:
* `acceptsSignal`
* `addDevice`
* `removeDevice`
* `getAvailableDevices`
* `getAvailableDeviceTypes`
=> Add missing RPCs (remote procedure calls)

docs/Antora/modules/getting_started/nav-getting_started.adoc, docs/Antora/modules/getting_started/pages/quick_start.adoc, docs/Antora/modules/getting_started/pages/quick_start_application.adoc, docs/Antora/modules/getting_started/pages/quick_start_building_opendaq.adoc, docs/Antora/modules/getting_started/pages/quick_start_setting_up_csharp.adoc
Added the missing documentation and linked it in other documents where applicable.
~P.S.: only the last commit relevant (`.NET Bindings - Created quick_start_setting_up_csharp.adoc`) as it is based on PR #542~
=> [TBBAS-1808] .NET Bindings - Fill in setting-up guide for .NET in "Getting started"

.github/ISSUE_TEMPLATE/1-BUG-REPORT.yml, docs/Antora/modules/howto_guides/pages/howto.adoc
=> Update bug report form to include programming language and change `howto.adoc` order so it's the same across the board

examples/cpp/multi_reader_example/multi_reader_example.cpp
=> Fix multi reader example

core/coretypes/include/coretypes/ctutils.h, modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
=> Fix sprintf error on make error info with percentage in text 

examples/cpp/quick_start/quick_start_simulator.cpp, simulator/simulator_app/src/main.cpp
=> Update quick_start_simulator to vbox simulator

core/opendaq/modulemanager/include/opendaq/module_manager_impl.h, core/opendaq/modulemanager/src/module_manager_impl.cpp, modules/tests/test_opendaq_device_modules/test_default_config.cpp, modules/tests/test_opendaq_device_modules/test_helpers/test_helpers.h, modules/tests/test_opendaq_device_modules/test_streaming.cpp
=> <TBBAS-1826> Add PrimaryAddressType field to prioritize IPv4/v6 connections in add device general config

core/coreobjects/include/coreobjects/property_object_impl.h, shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
=> [Bug:] Fix update client property value while setting new value inside callback

.github/workflows/package.yml, .github/workflows/reusable_nuget_creation_and_test.yml, bindings/dotnet/openDAQ.Net/README.md, bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/OpenDAQ_CITests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net/media/README.md, bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
- To avoid having to manually rebuild the .NET Bindings without a beta version suffix, `package.yml` has been adapted to build the .NET Bindings and the NuGet package with the release version number.
- Some improvements were done to the readme and test files.
- Build number bumped up.
=> [TBBAS-1810] .NET Bindings - Prepare NuGet package (create release NuGet package in package.yml)

core/opendaq/modulemanager/src/module_manager_impl.cpp
=> Remove unnecessary daq try

.github/workflows/package.yml, .github/workflows/reusable_nuget_creation_and_test.yml, bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
Setting Job output has a different syntax in pwsh than bash.
I also added repo info to the package meta-data.
=> .NET Bindings - Fixed NuGet package creation in CI

core/opendaq/device/src/CMakeLists.txt
=> Install missing device_private headers

core/opendaq/device/include/opendaq/device_impl.h, core/opendaq/opendaq/tests/test_instance.cpp
=> Update user lock object when loading serialized device

core/opendaq/component/include/opendaq/component_impl.h, core/opendaq/device/tests/test_device.cpp, core/opendaq/signal/include/opendaq/signal_impl.h
Serialize the Active flag for all Components, and supplement the `DeviceTest.SerializeAndDeserialize` test with a quick check that would fail otherwise
=> Serialize the Active flag for all Components

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/package.yml, bindings/python/package/METADATA.in, bindings/python/package/build_pip.py, docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc, shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- Wheels metadata modified
- Docs modified
- CI workflows modified
- manylinux image changed manylinux2014 -> manylinux_2_28
- build warning fix
=> Python bindings Wheels 3.13

examples/python/gui_demo/components/add_device_dialog.py, examples/python/gui_demo/components/device_info_dialog.py
=> Fix python syntax errors

changelog/changelog_3.0.0-4.0.0.md, core/coreobjects/include/coreobjects/property_object.h, core/coreobjects/include/coreobjects/property_object_impl.h, core/coreobjects/tests/test_value_changed_events.cpp, core/opendaq/opendaq/include/opendaq/instance_impl.h, core/opendaq/opendaq/src/instance_impl.cpp, shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h, shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp, shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_property_object_impl.h, shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
- Add "Any read/write" events to property object.
- These events are triggered whenever any property value is read/written.
=> Add "onAny" property value read and write events

bindings/python/opendaq/generated/reader/py_multi_reader.cpp, bindings/python/tests/test_reader_datetime.py, docs/Antora/modules/howto_guides/pages/howto_read_aligned_signals.adoc
* **Multireader factory function** can use **native Python** `list` as parameters in addition to `IList`
* How-to guides for **Multireader** is updated to include **Python** examples
=> [TBBAS-1992][TBBAS-1994] Support for python lists in multireader and how-to guides update

examples/python/gui_demo.py, examples/python/gui_demo/components/add_function_block_dialog.py, examples/python/gui_demo/utils.py
* Nested FBs in Add FB dialog
* Add FB dialog could be called from tree popup menu 
* Close item is removed from tree popup menu
=> [TBBAS-2018] Support adding and removing nested function blocks in Python GUI

core/opendaq/device/include/opendaq/device_impl.h, core/opendaq/device/tests/test_device.cpp, core/opendaq/modulemanager/src/module_manager_impl.cpp, core/opendaq/opendaq/mocks/mock_device_module.cpp, core/opendaq/opendaq/tests/test_instance.cpp
=> Fix local device discovery and serialization on id clashes

examples/python/gui_demo/utils.py
This PR will properly show time domain signal last value
However, this is only a temporary solution. As a final solution, I propose a new core type, `IAbsTime`, and return this one as an object when calling `ISignal.getLastValue`. Cpp bindings should convert this type to `std::chrono::system_clock`˙and Python bindings should convert it to Python `datetime` object.
=> Show time domain signal last value as time

core/opendaq/component/src/CMakeLists.txt, core/opendaq/modulemanager/src/module_manager_impl.cpp, modules/ref_device_module/src/ref_device_impl.cpp
- remove coping modules in vector of modules
=> [TBBAS-2001] openDAQ module loading fails on Android

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/package.yml, .github/workflows/reusable_nuget_creation_and_test.yml, bindings/dotnet/openDAQ.Net/README.md, bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/openDAQ.Net.CI.Test.csproj, bindings/dotnet/openDAQ.Net/openDAQ.Net.NuGet.Test/openDAQ.Net.NuGet.Test.csproj, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDAQTestsBase.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqBackgroundInfoGuidesTests.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/openDAQ.Net.Test.csproj, bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coretypes/OpenDaqException.cs, bindings/dotnet/openDAQ.Net/openDAQ.Net/media/README.md, bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
- Modified the GitHub workflows (especially the .NET Bindings NuGet creation and testing).
- Fixed .NET Bindings tests that did not execute well under Linux
P.S.: It relies on PR #667 so that the .NET version bump-up also shows up in the changes for now.
=> [TBBAS-1130] .NET Bindings - Make tests run under Linux CI

examples/python/gui_demo.py, examples/python/gui_demo/components/add_device_dialog.py, examples/python/gui_demo/utils.py, examples/python/guide/how_to_multiread.py
[TBBAS-1994][TBBAS-2060] Clean up exceptions in GUI App and Multireader example
- Handle multiple found unhandled exceptions in Python GUI App
- Added MultiReader example for Python 
None
None
None
None
=> [TBBAS-1994][TBBAS-2060] Clean up exceptions in GUI App and Multireader example

bindings/python/core_objects/generated/py_property_object.cpp, bindings/python/core_types/generated/py_simple_type.cpp, bindings/python/core_types/generated/py_struct_builder.cpp, bindings/python/core_types/generated/py_struct_type.cpp, bindings/python/core_types/generated/py_type.cpp, bindings/python/opendaq/generated/component/py_component_status_container.cpp, bindings/python/opendaq/generated/component/py_component_status_container_private.cpp, bindings/python/opendaq/generated/functionblock/py_function_block.cpp, bindings/python/opendaq/generated/reader/py_multi_reader_builder.cpp
Commit changes after running `run_rtgen.sh`, thereby updating Python bindings
(all changes were auto-generated and manually fixed afterwards)
=> Apply `run_rtgen.sh`

docs/Antora/modules/knowledge_base/nav-knowledge_base.adoc, docs/Antora/modules/knowledge_base/pages/multireader_spec.adoc, examples/CMakeLists.txt, examples/cpp/CMakeLists.txt, examples/cpp/multi_reader_howto_example/CMakeLists.txt, examples/cpp/multi_reader_howto_example/read_different_rates.cpp, examples/cpp/multi_reader_howto_example/read_same_rates.cpp, examples/cpp/multi_reader_howto_example/read_same_rates_and_output.cpp
=> Add multireader specification document

examples/python/struct_properties.py
Added a struct core type usage example using the openDAQ Python bindings.
=> Structs example added

core/opendaq/reader/src/block_reader_impl.cpp, core/opendaq/reader/tests/test_block_reader.cpp, docs/Antora/modules/knowledge_base/pages/readers.adoc
=> Change the block reader `getAvailableCount()` behaviour

changelog/changelog_3.0.0-4.0.0.md, modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp, shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h, shared/libraries/discovery/src/daq_discovery_client.cpp, shared/libraries/discovery_server/include/discovery_server/mdnsdiscovery_server.h, shared/libraries/discovery_server/src/mdnsdiscovery_server.cpp
- Fixing the discovering multiple devices on the same ip
- fix serviceQualified in mdns server
=> Mdns discovering multiple devices with the same ip

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/package.yml, CMakeLists.txt, bindings/python/package/build_pip.py, bindings/python/py_opendaq_daq/CMakeLists.txt, cmake/openDAQUtils.cmake, modules/ref_fb_module/tests/test_ref_fb_module.cpp, modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
Python Wheels for MacOS
- Some cmake tweaks for MacOS builds
- `bindings/python/package/build_pip.py` changes to build MacOS wheels
- CI changes
Install and open GUI app
```shell
brew install python@3.13
python3.13 -m venv venv
source venv/bin/activate
pip install opendaq
python -m opendaq
```
None
None
None
=> [TBBAS-1948] Python bindings: MacOS Wheels

changelog/changelog_3.10-3.20.md
Updates changelog to better reflect all changes since 3.10
=> Update changelog since 3.10

changelog/changelog_3.10-3.20.md
Adds information about changes done in streaming base implementation by #606
=> Extend changelog info 

docs/Antora-specs/antora.yml, docs/Antora/antora.yml
Fixes openDAQ version in Antora docs
=> Fix Antora versioning (3.20)

changelog/changelog_3.10-3.20.md
Add missing items to changelog, move one item from features to bugs
=> Add missing items to changelog, move one item from features to bugs

core/coretypes/include/coretypes/ratio_ptr.h
Make RatioPtr.simplify() const function
=> Make RatioPtr.simplify const function

changelog/changelog_3.10-3.20.md
=> Fix PR number in changelog

core/coretypes/include/coretypes/objectptr.h
Implementing missed unequal operators for the object ptr
=> Implementing missed unequal operators for the object ptr

external/streaming_protocol/CMakeLists.txt
Changes used LT streaming client lib version to release 1.4.0
=> Use LT streaming client lib release version 1.4.0

cmake/Packing.cmake
Adds new LT server and csv module as cpack components.
=> Fix new LT and csv module install

docs/Antora/modules/explanations/pages/components.adoc, docs/Antora/modules/explanations/pages/device.adoc, docs/Antora/modules/explanations/pages/interfaces_objects_wrappers.adoc, docs/Antora/modules/explanations/pages/multireader_spec.adoc, docs/Antora/modules/explanations/pages/property_system.adoc, docs/Antora/modules/explanations/pages/protocol_features_characteristics.adoc, docs/Antora/modules/howto_guides/pages/howto_access_control_introduction.adoc, docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc, docs/Antora/modules/tutorials/pages/quick_start_building_opendaq.adoc, docs/Antora/modules/tutorials/pages/quick_start_setting_up_cpp.adoc, docs/Antora/modules/tutorials/pages/quick_start_setting_up_csharp.adoc, docs/Antora/modules/tutorials/pages/tutorial_application.adoc
Fixes some minor issues in Antora docs
=> Fix Antora notes

external/streaming_protocol/CMakeLists.txt
Revert LT changes since Release 1.2
=> Revert faulty LT changes

external/nlohmann_json/CMakeLists.txt, external/streaming_protocol/CMakeLists.txt, shared/libraries/websocket_streaming/include/websocket_streaming/signal_descriptor_converter.h, shared/libraries/websocket_streaming/src/signal_descriptor_converter.cpp
Upgrade **nlohmann-json** from **3.10.2** to **3.11.3** and related code
- nlohmann-json required version changed
- dependent code update
- streaming-lt version changed
**None**
**None**
**None**
**None**
=> [TBBAS-2555] Upgrade nlohmann-json 3.10.2 To 3.11.3

changelog/changelog_3.10-3.20.md, core/opendaq/CMakeLists.txt, core/opendaq/functionblock/tests/CMakeLists.txt, core/opendaq/modulemanager/src/CMakeLists.txt, core/opendaq/signal/src/CMakeLists.txt, examples/modules/basic_csv_recorder_module/src/basic_csv_recorder_impl.cpp, modules/new_websocket_streaming_server_module/src/new_websocket_streaming_server_impl.cpp, modules/new_websocket_streaming_server_module/src/websocket_server.cpp, shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h
=> Merge 3.20 -> Main

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/package.yml
Install NSIS in CI on RC branch thereby fixing cpack error
=> Install NSIS on RC branch

examples/applications/python/Integration Examples/custom_file_logger_sinks.py
Added a logger sinks example in python.
Added Python logger sink example
examples/custom_file_logger_sinks.py
None
None
None
=> Custom file logger sinks python example
