openDAQ/openDAQ

- bindings/python/core_types/CMakeLists.txt
- bindings/python/core_types/include/py_core_types/py_core_types.h
- bindings/python/core_types/src/py_base_object.cpp
- bindings/python/core_types/src/py_core_types.cpp
- bindings/python/py_opendaq_daq/src/opendaq_daq.cpp
This should fix the order of function declaration, so that `CoreType` enum is known to pybind11 before `IBaseObject` gets mapped. It should fix the error
```
pybind11_stubgen - [  ERROR] In opendaq.opendaq.IBaseObject.core_type. : Invalid expression 'daq::CoreType'
```
but it makes sense to have this one inside its own file/function anyway.
After adding support for `INumber` and this, the list of remaining errors for `pybind11_stubgen` is
```
pybind11_stubgen - [  ERROR] In opendaq.opendaq.ExternalAllocator : Can't find/import 'capsule'
pybind11_stubgen - [  ERROR] In opendaq.opendaq.IAllocator.allocate : Can't find/import 'capsule'
pybind11_stubgen - [  ERROR] In opendaq.opendaq.IAllocator.free : Can't find/import 'capsule'
pybind11_stubgen - [  ERROR] In …
```
> Split Python bindings for IBaseObject into its own file

- .github/workflows/ci.yml
- external/streaming_protocol/CMakeLists.txt
- modules/tests/test_opendaq_device_modules/test_streaming.cpp
- modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
- modules/tests/test_ws_siggen_integration/test_websocket_siggen.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_streaming_integration.cpp
- shared/libraries/websocket_streaming/include/websocket_streaming/input_signal.h
- shared/libraries/websocket_streaming/include/websocket_streaming/signal_info.h
- shared/libraries/websocket_streaming/include/websocket_streaming/streaming_client.h
- shared/libraries/websocket_streaming/include/websocket_streaming/websocket_client_device_impl.h
- shared/libraries/websocket_streaming/src/input_signal.cpp
- shared/libraries/websocket_streaming/src/output_signal.cpp
- shared/libraries/websocket_streaming/src/signal_descriptor_converter.cpp
- shared/libraries/websocket_streaming/src/streaming_client.cpp
- shared/libraries/websocket_streaming/src/websocket_client_device_impl.cpp
- shared/libraries/websocket_streaming/tests/test_signal_descriptor_converter.cpp
openDAQ Websocket streaming client changes:
* received time/value signal meta info can be correctly handled independently from order of receiving
* `absoluteReference` streaming signal meta is converted into origin value of openDAQ signal - it fixes renderer time axis values
* `tableId` of time/value signals allowed to be not-equal to `signalId` of value signal
* name from descriptor is used as signal `"Name"` property instead of using signalId for signals of websocket pseudo device
> Websocket streaming alignment part 2

- core/opendaq/opendaq/src/client_impl.cpp
- shared/libraries/discovery/include/daq_discovery/daq_discovery_client.h
- shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
* 'getAvailableDevices' per-module calls are executed in parallel on separate threads
* set the mDNS query response wait timeout to be determined by a custom duration value (1s default) rather than a fixed 2-second timeout.
> <TBBAS-1168> Optimize device enumeration/discovery duration

- examples/python/gui_demo.py
- modules/tests/test_opendaq_device_modules/CMakeLists.txt
- modules/tests/test_ws_siggen_integration/CMakeLists.txt
- modules/tests/test_ws_siggen_integration/test_websocket_siggen.cpp
- modules/websocket_streaming_client_module/include/websocket_streaming_client_module/websocket_streaming_client_module_impl.h
- modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
- modules/websocket_streaming_client_module/tests/test_websocket_streaming_client_module.cpp
- shared/libraries/websocket_streaming/include/websocket_streaming/streaming_client.h
- shared/libraries/websocket_streaming/src/streaming_client.cpp
- shared/libraries/websocket_streaming/src/websocket_client_device_impl.cpp
- shared/libraries/websocket_streaming/src/websocket_streaming_impl.cpp
- shared/libraries/websocket_streaming/tests/test_streaming.cpp
* pseudo device can be alternatively connected using raw tcp sockets by prefix `daq.tcp://`
* enable gui_app to connect any type (not only opcua) of device by user defiined connection string: 
`python gui_demo.py --connection_string daq.tcp://127.0.0.1:7411`
> Enable streaming-lt pseudo device connection using TCP sockets

- changelog/changelog_2.0.0-3.0.0.txt
- core/coreobjects/include/coreobjects/core_event_args.h
- core/coreobjects/include/coreobjects/core_event_args_factory.h
- core/coreobjects/include/coreobjects/core_event_args_ids.h
- core/coreobjects/include/coreobjects/core_event_args_impl.h
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/src/CMakeLists.txt
- core/coreobjects/src/core_event_args_impl.cpp
- core/coretypes/include/coretypes/event_args_impl.h
- core/opendaq/component/include/opendaq/component_impl.h
- core/opendaq/component/tests/CMakeLists.txt
- core/opendaq/component/tests/test_component.cpp
- core/opendaq/component/tests/test_core_event.cpp
- core/opendaq/context/include/opendaq/context.h
- core/opendaq/context/include/opendaq/context_ptr.fwd_declare.h
- core/opendaq/context/src/CMakeLists.txt
- core/opendaq/modulemanager/include/opendaq/context_impl.h
- core/opendaq/modulemanager/src/context_impl.cpp
- core/opendaq/opendaq/mocks/include/opendaq/gmock/context.h
Initial PR for the SDK core support for events that trigger when the core is changed. This PR includes the global event attached to the context, as well as the event triggers for property object changes.
> Add core event triggers for Property Object

- bindings/python/core_types/src/py_converter.cpp
- bindings/python/tests/test_property_system.py
Fix the bug causing impossibility to use container properties without explicit conversion, for example
`property_object.get_property_value('list')[0]`
> [TBBAS-959] Fix: Container properties require explicit conversion before usage

- core/coreobjects/include/coreobjects/property_object.h
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/tests/test_property_object.cpp
- core/opendaq/opendaq/tests/test_core_events.cpp
- shared/libraries/opcuatms/opcuatms_server/tests/test_tms_property_object.cpp
When calling `setPropertyValue`, the value should not be written, nor should a "write" event be triggered if the value is equal to the previously written one, or the default (if no local value is present)
> Skip writing Property object values if they do not constitute a value change

- bindings/python/opendaq/generated/component/py_component.cpp
- bindings/python/opendaq/generated/component/py_component_private.cpp
- bindings/python/opendaq/generated/component/py_search_filter.cpp
- bindings/python/opendaq/generated/context/py_context.cpp
- bindings/python/tests/test_property_system.py
- changelog/changelog_2.0.0-3.0.0.txt
- core/coreobjects/include/coreobjects/core_event_args.h
- core/coreobjects/include/coreobjects/core_event_args_factory.h
- core/coreobjects/include/coreobjects/property.h
- core/coreobjects/include/coreobjects/property_builder_impl.h
- core/coreobjects/include/coreobjects/property_impl.h
- core/coreobjects/include/coreobjects/property_object.h
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/include/coreobjects/property_object_internal.h
- core/coreobjects/src/core_event_args_impl.cpp
- core/coreobjects/tests/test_property_object.cpp
- core/opendaq/component/include/opendaq/component_private.h
- core/opendaq/functionblock/tests/test_fb_wrapper.cpp
- core/opendaq/opendaq/src/CMakeLists.txt
- core/opendaq/opendaq/tests/test_core_events.cpp
- core/opendaq/opendaq/tests/test_instance.cpp
- docs/Antora/modules/background_info/pages/property_system.adoc
- docs/tests/test_property_system.cpp
- modules/ref_device_module/src/CMakeLists.txt
- shared/libraries/opcuatms/tests/opcuatms_integration/test_property_object_advanced.cpp
Object-type properties as of now behaved differently than any other property type. They were not frozen on add to property objects, but were frozen when added to property object classes. This was made more consistent by always freezing them, but also creating a local clone of the object that is returned to users on `getPropertyValue`. That clone can be edited.
Additionally, Property object core events now contain the path to the property if the property is contained within a nested property object.
> Freeze and clone nested object-type property default values

- bindings/python/core_types/src/py_list.cpp
- bindings/python/tests/test_core_type_string.py
- bindings/python/tests/test_core_types.py
- bindings/python/tests/test_property_system.py
- docs/Antora/modules/background_info/pages/components.adoc
- docs/Antora/modules/background_info/pages/device.adoc
- docs/Antora/modules/background_info/pages/function_blocks.adoc
- docs/Antora/modules/background_info/pages/modules.adoc
- docs/Antora/modules/background_info/pages/property_system.adoc
- docs/Antora/modules/howto_guides/pages/howto_configure_function_block.adoc
- docs/Antora/modules/howto_guides/pages/howto_save_load_configuration.adoc
- examples/python/gui_demo.py
- Fix naming of functions and variables according Python's conventions
- Other minor fixes
> [TBBAS-1219] Python: Get rid of camel case notation in code and docs

- external/streaming_protocol/CMakeLists.txt
- shared/libraries/websocket_streaming/include/websocket_streaming/input_signal.h
- shared/libraries/websocket_streaming/include/websocket_streaming/signal_descriptor_converter.h
- shared/libraries/websocket_streaming/include/websocket_streaming/streaming_client.h
- shared/libraries/websocket_streaming/include/websocket_streaming/streaming_server.h
- shared/libraries/websocket_streaming/src/input_signal.cpp
- shared/libraries/websocket_streaming/src/streaming_client.cpp
- shared/libraries/websocket_streaming/src/streaming_server.cpp
- shared/libraries/websocket_streaming/tests/CMakeLists.txt
- shared/libraries/websocket_streaming/tests/mock_streaming_server.cpp
- shared/libraries/websocket_streaming/tests/mock_streaming_server.h
- shared/libraries/websocket_streaming/tests/streaming_test_helpers.h
- shared/libraries/websocket_streaming/tests/test_websocket_client_device.cpp
* Allow multiple data signals to have same `tableId`
* Add client handling of domain signals listed as available
* Add `MockStreamingServer` implementation used in tests to bypass the creation of artificial time signals within the streaming-lt library
* Expand the WebSocket pseudo device test suite with the relevant tests
> <TBBAS-1210> Enable support of shared domain signals in websocket streaming client

- .github/workflows/deploy.yml
When `deploy.yml` is run, two jobs for Windows are running. One for x64 and one for Win32.
Before the generated package is written to AWS S3, the old one should be deleted there.
Until now, that cleanup was deleting all packages.
This fix distinguishes between x64 and Win32 build to remove only the platform dependent file from S3.
The mechanism can be checked in branch [ci/deploy-rm-filter-test](https://github.com/openDAQ/openDAQ/tree/ci/deploy-rm-filter-test), upload section of the action run ("filter test for deploy on AWS").
> Fixed deployment cleanup filter for AWS

- core/opendaq/component/src/CMakeLists.txt
It seems that core headers tags_impl.h and component_keys.h, as well as RTGen'd deserialize_component headers, have either recently been added, or have recently been included from other public headers in the SDK. Consequently they now seem to be required. However, they are not installed (they're missing from SRC_PublicHeaders in core/opendaq/component/src/CMakeLists.txt).
See top.
> install missing public core headers

- shared/libraries/opcua/opcuashared/include/opcuashared/opcuavariant.h
- shared/libraries/opcua/opcuashared/src/opcuavariant.cpp
- shared/libraries/opcuatms/opcuatms/src/converters/core_types_converter.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_fusion_device.cpp
Structs and so opc ua variants can have also variables with the opc ua type float. These need to be mapped in the correct way.
> Bugfix: Float Type not supported in Structures

- cmake/RTGen.cmake
- [N/A] I have made corresponding changes to the documentation
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] Any dependent changes have been merged and published in downstream modules
This PR fixes a bug that appears when compiling with `-DOPENDAQ_ENABLE_NATIVE_STREAMING=ON`:
[ 98%] Generating bindings for: config_client_object.h
Warning: Error occurred while generating the output file: Failed to copy the generated file to the output directory.
make[2]: *** [shared/libraries/config_protocol/src/CMakeFiles/opendaq_config_protocol.dir/build.make:80: shared/libraries/config_protocol/include/config_protocol/config_client_object_ptr.h] Error 4
make[1]: *** [CMakeFiles/Makefile2:6479: …
> fix OPENDAQ_ENABLE_NATIVE_STREAMING: always create RTGen output dir if it doesn't exist

- core/opendaq/component/include/opendaq/component_impl.h
- core/opendaq/functionblock/src/CMakeLists.txt
- core/opendaq/reader/tests/test_multi_reader.cpp
On the following link, you can find more info about this issue: [Inline static destructors are called multiple times, once for each cpp including it](https://developercommunity.visualstudio.com/t/inline-static-destructors-are-called-multiple-time/1157794)
I used the suggested workaround.
> Inline static destructors are called multiple times (VS 2017 compiler bug)

- modules/ref_fb_module/src/trigger_fb_impl.cpp
- modules/ref_fb_module/tests/test_fb_trigger.cpp
Use PacketReadyNotification::Scheduler instead of PacketReadyNotification::SameThread but also stop the Scheduler as a temporary fix in Trigger function block implementation.
> Use Scheduler in Trigger function block implementation with a temporary workaround

- core/opendaq/reader/include/opendaq/multi_reader.h
- core/opendaq/reader/include/opendaq/multi_reader_impl.h
- core/opendaq/reader/include/opendaq/multi_typed_reader.h
- core/opendaq/reader/include/opendaq/reader_factory.h
- core/opendaq/reader/src/multi_reader_impl.cpp
- core/opendaq/reader/tests/test_multi_reader.cpp
At some point, there will be too many factories and their parameters. We should rework the multi-reader either to accept a single object that consists of many parameters, i.e., IMultiReaderCreateParams, or even better to make a builder pattern of multi-reader construction.
> Add option to multi reader to start reading on the full unit of the domain

- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/tests/amplifier_test.cpp
Setting property while an object was being updated performed all validation/coercion/binding operations and stored the evaluated value in a list of values to be written on `endUpdate`. This did not take into account that a value change can impact future write operations done during the update.
This bugfix moves the validation/coercion/binding to the `endUpdate` call where the instead of simply storing the new value into the local value map, `setPropertyValue` is called.
> Apply properties on update end in order

- core/coreobjects/include/coreobjects/eval_value_parser.h
- core/coreobjects/src/eval_value_parser.cpp
- core/coreobjects/tests/test_evalvalue.cpp
This replaces the majority of recursive descend parsing with
Pratt parser, simplifying much of the code. The EvalValue
consists of only expressions, so we don't need most of the
recursive descent stuff.
> Eval value parser simplification

- core/opendaq/signal/include/opendaq/signal_impl.h
I used a solution from https://github.com/openDAQ/openDAQ/pull/127 also for SignalBase.
> Inline static destructors are called multiple times (VS 2017 compiler bug) (Part 2)

- shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_device_impl.h
- shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_device.cpp
Fix for TmsClientDevice::GetTicksSinceOrigin if the domain is not fetched yet.
> Fix first call of TmsClientDevice::GetTickSinceOrigin

- CMakePresets.json
Just missed to add `"OPENDAQ_GENERATE_CSHARP_BINDINGS": true,` to the "package" preset so that the .NET Bindings will be generated in `deploy.yml`.
> Added .NET Bindings generation flag to cmake preset "package"

- modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
- modules/native_streaming_client_module/src/native_device_impl.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
Device info is now a field in common DeviceImpl and is deserialized in native configuration protocol. Connection string is overriden.
> Reuse existing device info transfered via native protocol

- .github/workflows/deploy.yml
When the .NET Bindings are being built, they already get the short SHA hash value for setting its version number. So the later renaming is no longer necessary.
> .NET Bindings - NuGet package name already contains SHA for AWS

- core/coreobjects/include/coreobjects/eval_value_parser.h
- core/coreobjects/tests/test_evalvalue.cpp
Now that I had a chance to play with EvalValue a bit more in real-life examples, I think
it makes a lot more sense for logical or & and operators to have precedence lower than
(in)equality checking. This allows for more "natural" (i.e. c-like) expressions: 
`$value == 1 || $value > 3` with this patch parses as `($value == 1) || ($value > 3)` 
instead of `$value == (1 || $value) > 3` as it would before.
> Swap EvalValue precedence for logic and equality operators

- modules/native_streaming_client_module/src/native_device_impl.cpp
Previous version throws "owner already assigned"
> Fix native device device info with custom fields

- shared/libraries/config_protocol/include/config_protocol/config_protocol.h
- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- shared/libraries/config_protocol/src/config_protocol.cpp
- shared/libraries/config_protocol/src/config_protocol_client.cpp
- shared/libraries/config_protocol/tests/CMakeLists.txt
- shared/libraries/config_protocol/tests/test_config_packet.cpp
The packet header size should be the same on all platforms.
> Native config protocol has the wrong packet header size on the armv7l

- core/coreobjects/include/coreobjects/property_object_impl.h
- shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
This caused deadlock when client called update -> server side update event comes to client -> client recursively calls begin/end update on children caused command to be sent to server.
> Fix server side update calling begin/end update

- external/streaming_protocol/CMakeLists.txt
- shared/libraries/signal_generator/src/signal_generator.cpp
- shared/libraries/websocket_streaming/include/websocket_streaming/output_signal.h
- shared/libraries/websocket_streaming/src/output_signal.cpp
Integrates the latest modifications of Streaming-lt library
> <TBBAS-1453> Write start domain value only upon signal subscribing in streaming-lt server

- bindings/python/core_types/generated/py_enumeration.cpp
- bindings/python/core_types/generated/py_enumeration_type.cpp
- bindings/python/core_types/generated/py_type_manager.cpp
- bindings/python/tests/test_core_types.py
- Make Enumeration and EnumerationType behave close to native Python enums
- Tests updated
- Usage example is in the testcase
> [TBBAS-1367] Make Enumeration and EnumerationType behave close to native Python enums

- bindings/python/package/METADATA.in
- bindings/python/package/build_pip.py
With this commit, running `py -m opendaq [args]` directly executes the tk GUI example. Having a quick access to a GUI for openDAQ seems like a really nice feature.
This might be controversial so feel free to just close the pull request. Would appreciate a check by @mojca and @Yarikk26 as well.
> Add python gui example as openDAQ package's __main__ entrypoint

- core/opendaq/component/include/opendaq/component.h
- core/opendaq/component/include/opendaq/component_impl.h
- core/opendaq/component/include/opendaq/folder_impl.h
- core/opendaq/device/include/opendaq/device_impl.h
- core/opendaq/device/tests/test_tree_traversal.cpp
- core/opendaq/functionblock/include/opendaq/function_block_impl.h
- core/opendaq/opendaq/mocks/include/opendaq/gmock/input_port.h
- core/opendaq/signal/include/opendaq/signal_container_impl.h
- core/opendaq/signal/src/connection_impl.cpp
- core/opendaq/signal/tests/test_signal.cpp
- shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h
- shared/libraries/config_protocol/tests/test_core_events.cpp
- Connections no longer enqueue packets if input port is inactive.
- `setActive` now recursively sets the active flag of all children
> Recursive active call + input port logic

- core/coretypes/include/coretypes/type_manager_impl.h
- core/coretypes/src/struct_builder_impl.cpp
- core/coretypes/src/type_manager_impl.cpp
- core/coretypes/tests/test_type_manager.cpp
- shared/libraries/opcuatms/opcuatms/include/opcuatms/core_types_utils.h
- shared/libraries/opcuatms/opcuatms/src/converters/core_types_converter.cpp
- shared/libraries/opcuatms/opcuatms/src/core_types_utils.cpp
- shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_context.h
- shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/tms_client.h
- shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_context.cpp
- shared/libraries/opcuatms/opcuatms_client/src/tms_client.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property_object.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_property_object_advanced.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_fusion_device.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/tms_object_integration_test.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/tms_object_integration_test.h
- OPC UA structs that have a SDK native conversion are always converted to the SDK type
- List of reserved type names was added to type manager
- Tests for reserved type names in core
> Allow convertible openDAQ structs over OPC UA

- core/coretypes/include/coretypes/struct_builder_ptr.h
- core/opendaq/reader/tests/test_stream_reader.cpp
- core/opendaq/signal/include/opendaq/binary_data_packet_impl.h
- core/opendaq/signal/include/opendaq/data_packet.h
- core/opendaq/signal/include/opendaq/data_packet_impl.h
- core/opendaq/signal/include/opendaq/signal.h
- core/opendaq/signal/include/opendaq/signal_impl.h
- core/opendaq/signal/src/data_descriptor_impl.cpp
- core/opendaq/signal/tests/test_data_descriptor.cpp
- core/opendaq/signal/tests/test_data_packet.cpp
- core/opendaq/signal/tests/test_signal.cpp
- docs/Antora/modules/background_info/pages/signals.adoc
- docs/tests/test_signals.cpp
Support getLastValue for structs in core, enable converting data descriptors to struct types for structs, enable recursively building structs form packets, and fix bug in struct builder implementation. Some test are also added for getLastValue for structs.
> Support getLastValue for structs in core and fix bug in struct builder with tests

- core/coretypes/include/coretypes/intfs.h
- core/opendaq/reader/src/multi_reader_impl.cpp
- core/opendaq/reader/tests/test_multi_reader.cpp
Objects with weak ref support crash if weak ref has been added in constructor. This is my attempt at solving the issue. Perhaps there is a better way of doing it.
> Fix weak ref crashing in multi reader if exception is thrown in constructor

- bindings/python/opendaq/include/py_opendaq/py_typed_reader.h
Fixed a bug for timed versions of readers caused by not converting internal clock ticks to unix timestamps on Windows
> Time readers wrong timestamps on Windows bug fix

- simulator/Vagrantfile
- simulator/configurator.py
- simulator/opendaq-config.json
- simulator/simulator.service
* Serial number is determined by the actual MAC address
* Serial number is configured in services and localId is configured in `opendaq-config.json` on each boot (instead of once when creating the virtual machine) before `simulator.service` is started
* `simulator.service` is configured to start before `avahi-daemon.service`
* Fixed a typo in `opendaq-config.json`
> Fix serial number in simulator

- core/opendaq/opendaq/mocks/include/opendaq/gmock/streaming.h
- core/opendaq/opendaq/mocks/include/opendaq/mock/mock_streaming.h
- core/opendaq/opendaq/mocks/mock_streaming.cpp
- core/opendaq/opendaq/tests/test_instance.cpp
- core/opendaq/streaming/include/opendaq/mirrored_signal_impl.h
- core/opendaq/streaming/include/opendaq/streaming_impl.h
- core/opendaq/streaming/include/opendaq/streaming_private.h
- core/opendaq/streaming/tests/test_streaming.cpp
- modules/native_streaming_client_module/include/native_streaming_client_module/native_streaming_impl.h
- modules/native_streaming_client_module/src/native_streaming_impl.cpp
- modules/tests/test_opendaq_device_modules/test_streaming.cpp
- modules/tests/test_opendaq_device_modules/test_subdevices.cpp
- modules/tests/test_ref_modules/test_ref_modules.cpp
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/client_session_handler.h
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_client_handler.h
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/subscribers_registry.h
- shared/libraries/native_streaming_protocol/src/client_session_handler.cpp
- shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
- shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
- shared/libraries/native_streaming_protocol/src/subscribers_registry.cpp
- shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
- shared/libraries/websocket_streaming/include/websocket_streaming/streaming_client.h
- shared/libraries/websocket_streaming/include/websocket_streaming/websocket_streaming_impl.h
- shared/libraries/websocket_streaming/src/streaming_client.cpp
- shared/libraries/websocket_streaming/src/websocket_streaming_impl.cpp
> Native streaming: cache last event packet and send it to secondary subscribed client

- core/corecontainers/include/coretypes/listptr.h
- core/coretypes/tests/test_listobject.cpp
Fix memory leak of vector elements in ListPtr::toVector
> Fix memory leak in ListPtr::toVector

- shared/libraries/websocket_streaming/src/signal_descriptor_converter.cpp
- shared/libraries/websocket_streaming/tests/test_signal_descriptor_converter.cpp
> Fix - set start time param of linear rule to 0 for streaming-lt signals

- shared/libraries/opcua/opcuaserver/include/opcuaserver/opcuaaddnodeparams.h
- shared/libraries/opcua/opcuaserver/include/opcuaserver/opcuaserver.h
- shared/libraries/opcua/opcuaserver/src/opcuaaddnodeparams.cpp
- shared/libraries/opcua/opcuaserver/src/opcuaserver.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property_object.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_variable.cpp
- shared/libraries/ping/include/ping/icmp_header.h
In opendaq only objects had a nodeID as string. With this PR also Properties / Variables have a numeric node id.
> NodeId as String not as numeric for Properties

- cmake/openDAQConfig.cmake.in
This PR adjusts the openDAQConfig.cmake.in template file, which is used by find_package(openDAQ). There are two changes. The first is to use the correct path to openDAQUtils.cmake in all contexts (in particular include() contexts). The second is to include find_dependency(spdlog) which causes projects depending on openDAQ to also load spdlog, which is a required dependency; without this, projects using openDAQ must explicitly find_package(spdlog).
> cmake: find_dependency(spdlog) and fix path to openDAQUtils.cmake

- .github/workflows/ci.yml
Regression tests should be skipped for this PR, as I am trying to merge from a fork, which doesn't have the secrets available. I also intend to test if the tests are run when the secrets are available.
> Only perform regression tests when AWS secrets are available

- .github/workflows/deploy.yml
Downgrade benjlevesque/short-sha GitHub action from `@v3.0` to `@2.2` in `deploy.yml` for `manylinux2014 gcc Release` due to node 20 not available error
> Downgrade benjlevesque/short-sha

- bindings/python/opendaq/generated/device/py_device_info.cpp
- changelog/changelog_3.0.0-4.0.0.txt
- core/opendaq/device/include/opendaq/device_info.h
- core/opendaq/device/include/opendaq/device_info_impl.h
- core/opendaq/device/include/opendaq/device_info_internal.h
- core/opendaq/device/src/device_info_impl.cpp
- core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
- core/opendaq/modulemanager/src/module_manager_impl.cpp
- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- modules/native_streaming_client_module/tests/test_native_streaming_client_module.cpp
- modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
- modules/opcua_client_module/include/opcua_client_module/opcua_client_module_impl.h
- modules/opcua_client_module/src/opcua_client_module_impl.cpp
- modules/opcua_client_module/tests/test_opcua_client_module.cpp
- modules/opcua_server_module/src/opcua_server_impl.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
- modules/websocket_streaming_client_module/tests/test_websocket_streaming_client_module.cpp
- shared/libraries/websocket_streaming/src/websocket_streaming_server.cpp
- Take device caps as source of truth
- Add port to discovery caps
- Fall back to default port if not specified in cap
> Modify discovery capability merge

- shared/libraries/websocket_streaming/include/websocket_streaming/output_signal.h
- shared/libraries/websocket_streaming/include/websocket_streaming/streaming_server.h
- shared/libraries/websocket_streaming/src/output_signal.cpp
- shared/libraries/websocket_streaming/src/streaming_server.cpp
- shared/libraries/websocket_streaming/src/websocket_streaming_server.cpp
- shared/libraries/websocket_streaming/tests/test_streaming.cpp
- shared/libraries/websocket_streaming/tests/test_websocket_client_device.cpp
* protect concurrent data / meta-data writes vs signal subscribe / unsubscribe operations by the mutex lock
> Fix race condition within LT-streaming on signal unsubscribe:

- examples/python/gui_demo/components/input_port_row_view.py
- modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
- shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_device.cpp
* link streaming sources available per the device with the signals from added function block
* fix - create non-hierarchical references for added function block
* Python gui app - input port view - retrieve the connected signal directly from input port instead of getting it from connection to bypass OpcUa implementation limitations
> <TBBAS-1425> Enable streaming for signals of FB added via OpcUa

- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coretypes/include/coretypes/objectptr.h
- core/coretypes/tests/test_objectptr.cpp
- core/opendaq/component/include/opendaq/folder_impl.h
- core/opendaq/modulemanager/src/module_manager_impl.cpp
- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- shared/libraries/config_protocol/src/config_protocol_client.cpp
This PR is a side effect produced by debugging leaked device objects. The performance gain is insignificant, but I don't want to waste the effort.
> Replace some casts with borrow

- core/opendaq/opendaq/mocks/include/opendaq/mock/mock_fb.h
- core/opendaq/opendaq/mocks/mock_fb.cpp
- core/opendaq/signal/include/opendaq/signal_container_impl.h
- shared/libraries/opcuatms/opcuatms_server/tests/test_tms_function_block.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_function_block.cpp
- Add check to prevent duplicate signals in openDAQ component tree
> Re-add check for signal parent component

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .github/workflows/package.yml
Due to [GitHub actions transitioning to Node20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), the manylinux CI jobs are failing. This fix enforces the usage of Node16 in those actions.
> Force Node 16 usage in Manylinux CI

- .github/workflows/deploy.yml
- antora-specs-playbook-dev.yml
- antora-specs-playbook.yml
- docs/Antora-specs/.asciidoctorconfig
- docs/Antora-specs/README.md
- docs/Antora-specs/antora.yml
- docs/Antora-specs/modules/ROOT/nav-overview.adoc
- docs/Antora-specs/modules/ROOT/pages/overview.adoc
- docs/Antora-specs/modules/native_communication_protocol/nav-native-communication-protocol.adoc
- docs/Antora-specs/modules/native_communication_protocol/pages/activity_monitoring.adoc
- docs/Antora-specs/modules/native_communication_protocol/pages/configuration.adoc
- docs/Antora-specs/modules/native_communication_protocol/pages/examples.adoc
- docs/Antora-specs/modules/native_communication_protocol/pages/glossary.adoc
- docs/Antora-specs/modules/native_communication_protocol/pages/introduction.adoc
- docs/Antora-specs/modules/native_communication_protocol/pages/service.adoc
- docs/Antora-specs/modules/native_communication_protocol/pages/streaming.adoc
- docs/Antora-specs/modules/packet_streaming/nav-packet-streaming.adoc
- docs/Antora-specs/modules/packet_streaming/pages/data_packet.adoc
- docs/Antora-specs/modules/packet_streaming/pages/event_packet.adoc
- docs/Antora-specs/modules/packet_streaming/pages/examples.adoc
- docs/Antora-specs/modules/packet_streaming/pages/format.adoc
- docs/Antora-specs/modules/packet_streaming/pages/internal.adoc
- docs/Antora-specs/modules/packet_streaming/pages/overview.adoc
Adds an Antora versions of native protocols specs:
* [Packet streaming protocol](https://blueberrydaq.atlassian.net/wiki/spaces/~640b55549cba7ca0287bc6e0/pages/551288854/Packet+streaming+protocol+specification+draft)
* [Native communication protocol](https://blueberrydaq.atlassian.net/wiki/spaces/~640b55549cba7ca0287bc6e0/pages/544964610/openDAQ+native+communication+protocol+specification+draft)
The specifications are created separately from the user guide
> Antora documentation: native protocols specifications

- shared/libraries/opcua/opcuaserver/include/opcuaserver/opcuaaddnodeparams.h
- shared/libraries/opcua/opcuaserver/src/opcuaaddnodeparams.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_object.cpp
This bugfix fixes that property objects have a numeric NodeId if the parent has a string NodeId.
With this fix property objects have a String NodeId with this pattern <parentPath>/<browseName.>
It is requested that this bugfix goes also in the release branch 3.0.
> Bugfix: Property Object has Numeric Id

- shared/libraries/opcua/opcuaserver/include/opcuaserver/opcuaaddnodeparams.h
- shared/libraries/opcua/opcuaserver/src/opcuaaddnodeparams.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_object.cpp
This bugfix fixes that property objects have a numeric NodeId if the parent has a string NodeId.
With this fix property objects have a String NodeId with this pattern <parentPath>/<browseName.>
> Bugfix: Property Objects has Numeric Id

- core/coreobjects/include/coreobjects/property_object_impl.h
- core/opendaq/device/include/opendaq/address_info_impl.h
- core/opendaq/device/include/opendaq/server_capability_impl.h
- core/opendaq/device/src/address_info_impl.cpp
- core/opendaq/device/src/server_capability_impl.cpp
Property object cloning requires access to a protected object implementation method. Thus the objects are statically cast to the PropertyObjectImpl. This was implemented incorrectly when the Property object implementation is not the standard, base implementation, but is instead an implementation that makes use of the GenericPropertyObjectImpl class.
> Fix property object invalid cast on clone

- external/opendaq_dependency.cmake
- external/taskflow/CMakeLists.txt
- external/xxHash/CMakeLists.txt
This commit fixes the target-presence checks in opendaq_dependency(). Due to a bug, the checks were not previously being done at all. Now that they are, some libraries - like xxHash and Taskflow - needed some special handling, because they do not create their prefixed aliases (e.g. xxHash::xxhash) when used in FetchContent/add_subdirectory mode; these aliases are only created by the *Config.cmake files in config mode. So a new option ADD_FETCH_ALIAS is added to opendaq_dependency to create such aliases when a dependency is fetched with FetchContent. An additional pass-through option SOURCE_SUBDIR was added, which is passed through directly to FetchContent, to handle cases where the top-level CMake file is not in the repository's top directory (e.g. Arrow and xxHash).
> opendaq_dependency: fix target checks and better target suport

- antora-playbook-dev.yml
- antora-playbook.yml
- antora-specs-playbook-dev.yml
- antora-specs-playbook.yml
Bump `ui-bundle.zip` version of `antora-ui-spring` from release 1.3 to 1.4 to deploy [fix for `href` in openDAQ/antora-ui-spring](https://github.com/openDAQ/antora-ui-spring/commit/1cdd1bb885104983c0232450f15ec861394c2e46), using non-hard-coded link in `header-content.hbs`, which is used to build `ui-bundle.zip`, thereby fixing links from header logo image for:
* https://docs-dev.opendaq.com/manual
* https://docs.opendaq.com/manual
* https://opendaq.github.io/
which no longer all point to https://docs.opendaq.com, but instead to the appropriate user guide docs/manual home page.
Also [tested locally](https://github.com/openDAQ/openDAQ/actions/runs/10061657977).
> Bump `ui-bundle.zip` version of `antora-ui-spring` from release 1.3 to 1.4

- examples/python/gui_demo.py
- examples/python/gui_demo/components/attributes_dialog.py
- examples/python/gui_demo/components/properties_view.py
Python GUI App was displaying only that part of value before space character in TreeView widgets
> [TBBAS-1725] Python GUI App fix displaying values with spaces

- examples/python/gui_demo.py
add begin/end update to tree pop up:
- begin update starts function begin_update on PropertyObject
- end update starts function end_update on PropertyObject
- there is also visual indication if node is in process of updating
- modified tree traverse components recursive because I needed component names
> add begin/end update to tree pop up

- bindings/python/core_objects/generated/py_property_object.cpp
- bindings/python/tests/test_begin_end_update.py
- changelog/changelog_3.0.0-4.0.0.txt
- core/coreobjects/include/coreobjects/property_object.h
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/opendaq/opendaq/include/opendaq/instance_impl.h
- core/opendaq/opendaq/src/instance_impl.cpp
- examples/python/gui_demo.py
Adds `IPropertyObject.getUpdating(Bool* updating)` method to detect the begin/end update status on the property object.
The idea is to add begin/endUpdate support to the Python GUI demo app, and the new method is required to show the begin/endUpdate status.
> Add method to detect the update status of property object

- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
- modules/tests/test_opendaq_device_modules/test_subdevices.cpp
- modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
The test "NativeDeviceModulesTest.MultiClientReadChangingSignal" was failing due to  [issue](https://blueberrydaq.atlassian.net/browse/TBBAS-1740) with StreamReader timeouts mechanism.
The test was modified to avoid this issue by disabling the check, as it is not crucial for this particular test.
> Fix "NativeDeviceModulesTest.MultiClientReadChangingSignal" test

- .github/workflows/ci.yml
Bump version of `seanmiddleditch/gha-setup-ninja` used in `ci.yml` from `@v4` to `@v5`, thereby fixing deprecation warnings (`Node.js 16 actions are deprecated`)
> Bump version of `seanmiddleditch/gha-setup-ninja`

- bindings/python/core_types/include/py_core_types/py_converter.h
- bindings/python/opendaq/include/py_opendaq/py_typed_reader.h
This update uses standard `py::array` instead of typed `py::array_t<class T>`. There is no need to use type arrays here because the python array is anyway created with `dtype` parameter and not with template parameter. `toPyArray` first creates `py::array` and the it returns it as typed array, which is not necessary, as internally python arrays are not templated, the type is defined by local member.
> Simplify python reader return types, fix MSVC-2017 build

- bindings/python/core_objects/generated/py_property.cpp
- changelog/changelog_3.0.0-4.0.0.txt
- core/coreobjects/include/coreobjects/eval_value_helpers.h
- core/coreobjects/include/coreobjects/eval_value_impl.h
- core/coreobjects/include/coreobjects/property.h
- core/coreobjects/include/coreobjects/property_impl.h
- core/coreobjects/src/eval_value_impl.cpp
- core/coreobjects/tests/amplifier_test.cpp
- core/opendaq/functionblock/include/opendaq/property_wrapper_impl.h
- core/opendaq/functionblock/src/property_wrapper_impl.cpp
- core/opendaq/reader/include/opendaq/reader_status.h
- shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_amplifier.cpp
- Add `get/setValue` method to `IProperty`
- Allows easier access to the property's value when iterating through an object's properties
> Add IProperty get/setValue

- core/opendaq/functionblock/include/opendaq/function_block_impl.h
- core/opendaq/opendaq/mocks/include/opendaq/mock/mock_fb.h
- core/opendaq/opendaq/mocks/mock_fb.cpp
Removes unused config check in base FB implementation. Will later on be replaced in module manager and stored config for save/load.
> Remove redundant fb config check

- changelog/changelog_3.0.0-4.0.0.txt
- core/coreobjects/include/coreobjects/property_impl.h
- core/coreobjects/include/coreobjects/property_internal.h
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/tests/test_value_changed_events.cpp
- core/coretypes/include/coretypes/event.h
- core/coretypes/include/coretypes/event_impl.h
- core/coretypes/include/coretypes/event_ptr.h
- core/coretypes/include/coretypes/event_wrapper.h
- core/coretypes/src/event_impl.cpp
- Changed logic of `IProperty::getOnPropertyValueRead/Write` events.
- Now returns the owner's event when called, if the owner is assigned.
- A new function is available to get the class's event. That function is used internally to trigger class value change events.
> Update onPropertyRead/Write calling logic on owned properties

- core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
- core/opendaq/modulemanager/src/module_manager_impl.cpp
- modules/ref_device_module/src/ref_device_impl.cpp
- modules/tests/test_ref_modules/test_ref_modules.cpp
Allows to pass options as a part of a connection string.
This only works for device only config options for now.
> Allow passing of device options via connection string as url options

- bindings/dotnet/openDAQ.Net/openDAQDemo.Net/AttributeItem.cs
- bindings/dotnet/openDAQ.Net/openDAQDemo.Net/PropertyItem.cs
- bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmEditComponent.Designer.cs
- bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmEditComponent.cs
- bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmEditComponent.resx
- bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmInputDialog.cs
- bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmMain.Designer.cs
- bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmMain.cs
`Device` and `FunctionBlock` shows `InputPort`s and/or output `Signal`s with their `LastValue` (updated in an 1 second interval).
(Output-) `Signal` attributes don’t show signal descriptor and signal-domain descriptor yet like it is done in python Demo (expandable table too complex for standard WinForms controls).
It also contains a fix where editing a float value did not check min/max range correctly (check always failed).
> [TBBAS-1741] .NET Bindings - GUI demo displays inputs/outputs and can configure

- core/opendaq/modulemanager/src/module_manager_impl.cpp
- core/opendaq/synchronization/src/CMakeLists.txt
- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- modules/opcua_client_module/src/opcua_client_module_impl.cpp
- modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
- shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
- shared/libraries/websocket_streaming/src/streaming_client.cpp
- Primary connection string is changed if the address is unreachable
- IPv6 connection strings can include link local interface identifier
> IPv6 link local address interface added to connection string; connection string reachability check

- examples/python/gui_demo.py
- examples/python/gui_demo/components/attributes_dialog.py
- examples/python/gui_demo/components/properties_view.py
* Call `ttk.Style().configure("Treeview.Heading", font='Arial 10 bold')` once in `gui_demo.py` instead of multiple times (on click)
* Fix a bug where if you click the gear icon throughout the Python GUI Demo app, for example `open app -> click OpenDAQClient -> gear icon (top right)`, this would shift the underlying GUI in an unexpected way (expanding the Properties view right slightly and shrinking the Output Signals view somewhat)
> Fix Python GUI Demo app gear icon click action

- examples/python/gui_demo/app_context.py
- shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h
- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
The new version of client could not connect to the device without sync component as it was not found. The exception was replaced with warning. In gui demo the device was registered in dictionary with the typed connection string. If connection string prefix is "daq://" the device automatically chooses the optimal way of connection and stores not the connection string with "daq://" but with the preferred protocol which makes impossible to remove device as the connection string is different
> [BUG]: sync component  backwards compatibility. Removing the device in gui demo

- core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
- core/opendaq/modulemanager/src/module_manager_impl.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- Streaming now uses the address used by configuration when establishing connections.
- Refactored device creation code in module manager
> Prefer same address when establishing streaming connections

- core/opendaq/signal/include/opendaq/input_port_config_ptr.custom.h
`core/opendaq/signal/include/opendaq/input_port_config_ptr.custom.h` contained inconsistent whitespace: in half a dozen lines, 4 spaces were used instead of tabs. Most of the file used tabs. This mixture of whitespace formats leads to compiler warnings like:
error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
Furthermore these warnings are treated as errors in release mode - even, confusingly, if `OPENDAQ_RELEASE_WARNINGS_AS_ERRORS` is set to `OFF`.
> Fix inconsistent whitespace in input port custom header

- core/opendaq/signal/include/opendaq/input_port_config_ptr.custom.h
`core/opendaq/signal/include/opendaq/input_port_config_ptr.custom.h` contained inconsistent whitespace: in half a dozen lines, 4 spaces were used instead of tabs. Most of the file used tabs. This mixture of whitespace formats leads to compiler warnings like:
error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
> fix mismatched whitespace, causing compiler warnings

- docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
Makes it easier to discriminate between latest major release (eg. 3.0.0) vs. latest main wheel installation in the Antora docs.
I would also suggest considering https://pip.pypa.io/en/stable/cli/pip_install/#install-pre or similar for minor and/or patch versions of the SDK.
> Make Python wheel install instructions explicit

- core/coreobjects/include/coreobjects/permission_manager.h
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/opendaq/component/include/opendaq/component_impl.h
- core/opendaq/opendaq/tests/test_access_control.cpp
Property objects without parents had no access by default. Any type objects getters (eg. getAvailableFunctionBlockType) were crashing over native due to it.
- Add test
> Fix object permissions without owner

- modules/ref_fb_module/include/ref_fb_module/struct_decoder_fb_impl.h
- modules/ref_fb_module/src/CMakeLists.txt
- modules/ref_fb_module/src/ref_fb_module_impl.cpp
- modules/ref_fb_module/src/struct_decoder_fb_impl.cpp
- modules/ref_fb_module/tests/CMakeLists.txt
- modules/ref_fb_module/tests/test_fb_struct_decoder.cpp
- modules/ref_fb_module/tests/test_ref_fb_module.cpp
- modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
Adds a struct decoder function block that decomposes the struct signal into sub-signals. Signals are created when the data descriptor changed event is handled.
Tested with Python GUI demo and CAN channel; unit tests are still missing.
Update 1:
Added unit tests
> Add struct decoder function block

- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- shared/libraries/config_protocol/src/config_protocol_client.cpp
* Ensure thread-safe generation of unique ID for config request
* Instantiate a separate deserializer for parsing each config request reply
> Improve thread-safety of config protocol client

- modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
- modules/native_streaming_client_module/src/native_device_impl.cpp
- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
* Move ConnectionStatus initialization after deserialization finished
> Fix issue with native device custom statuses

- bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/CoreTypesBaseObjectTests.cs
- core/coretypes/src/boolean_impl.cpp
- core/coretypes/src/float_impl.cpp
- core/coretypes/src/integer_impl.cpp
- core/coretypes/src/intfs.cpp
When an instance/device/function block is created, several hundred objects are allocated. This PR pre-allocates and caches the most often used core types and increments the reference when the factory is called. It drastically reduces the number of malloc calls and object instantiations.
> Optimize number of core type objects instantiations

- .github/workflows/deploy.yml
Fixes the following CI error in in `deploy.yml`, that occurs while building the simulator:
```
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.
```
Successful workflow run after applying the fix: https://github.com/openDAQ/openDAQ/actions/runs/11127510502
> Simulator CI build error fix

- .github/pull_request_template.md
- cmake/openDAQConfig.cmake.in
- docs/Antora/modules/howto_guides/pages/howto.adoc
While following the cpp “getting started” guide here https://docs-dev.opendaq.com/manual/opendaq/3.4.0/getting_started/quick_start_setting_up_cpp.html,  there is an issue with the spdlog dependency in the first step of building the project (while executing `cmake -DCMAKE_BUILD_TYPE=Release -Bbuild .`). This dependency is already included in the openDAQ SDK and should not be referenced as an external dependency, at least not in this manner.
Follow https://docs-dev.opendaq.com/manual/opendaq/3.4.0/getting_started/quick_start_setting_up_cpp.html up until building the project.
In the first step of building the project (executing `cmake -DCMAKE_BUILD_TYPE=Release -Bbuild .`), the following error appears: 
```
Could not find a package configuration file provided by "spdlog" with any
of the …
```
> Fix `spdlog` dependency

- core/coreobjects/tests/test_value_changed_events.cpp
- core/coretypes/include/coretypes/event_impl.h
Introduces recursive mutex for events to avoid deadlocks.
> Change event mutex to recursive

- changelog/changelog_3.0.0-4.0.0.txt
- shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
- shared/libraries/config_protocol/include/config_protocol/errors.h
- shared/libraries/config_protocol/include/config_protocol/exceptions.h
- shared/libraries/config_protocol/src/CMakeLists.txt
- shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
- Bugfix where onPropertyValueWrite/Read events were available on the native protocol client, but were not fully supported.
- Said property object events were disabled to reduce probability of misuse.
- CoreEvents should be used instead of onWrite/Read events where needed.
> Disable config client property object onWrite/Read events

- core/coreobjects/tests/test_property_object.cpp
- core/coretypes/src/enumeration_impl.cpp
Enumeration construction with an integer parameter failed due to a type (`break` instead of `return`).
> Fix enumeration factory with integer parameter

- shared/libraries/opcuatms/opcuatms_client/include/opcuatms_client/objects/tms_client_property_object_impl.h
- shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property_object.cpp
- shared/libraries/opcuatms/opcuatms_server/tests/test_tms_device.cpp
- shared/libraries/opcuatms/opcuatms_server/tests/test_tms_property_object.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_property_object.cpp
- Allows calling `setProtectedPropertyValue()` over OPC UA.
- All server side callbacks on the OPC UA server are now interpreted as protected writes. 
- Previously, a write over OPC UA to a read-only property would result in a mismatched state between the SDK core and OPC UA server where the core had the new value, while the core had the old one.
> Enable protected write calls over OPC UA

- core/opendaq/streaming/include/opendaq/streaming_impl.h
- core/opendaq/streaming/tests/test_streaming.cpp
- modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
- modules/native_streaming_client_module/src/native_device_impl.cpp
- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- shared/libraries/config_protocol/tests/test_core_events.cpp
- shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
* Add a new Bool-type option in the native device config - RestoreClientConfigOnReconnect (default is False)
* Enable signals to become unavailable in native streaming during the reconnection is in progress
> Add an option to restore client-side configuration on reconnection

- examples/python/gui_demo/components/properties_view.py
The ordering of properties as defined in function blocks and other components is usually quite important. In a nicely designed system, properties beneath are affected by properties above but not the other way around. When properties are sorted lexicographically by name, these relations are lost.
> Stop sorting properties by name in python GUI

- shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
- shared/libraries/config_protocol/tests/test_config_protocol_access_control.cpp
- shared/libraries/config_protocol/tests/test_config_protocol_device_locking.cpp
beginUpdate & endUpdate optimizations don't work in some edge cases. I need to take a second look. Until then the changes will be reverted
> Temporary revert beginUpdate/endUpdate optimizations

- bindings/python/core_objects/generated/py_authentication_provider.cpp
- bindings/python/core_objects/generated/py_callable_info.cpp
- bindings/python/opendaq/generated/device/py_device.cpp
- changelog/changelog_3.0.0-4.0.0.txt
- core/coreobjects/include/coreobjects/callable_info.h
- core/coreobjects/include/coreobjects/callable_info_factory.h
- core/coreobjects/include/coreobjects/callable_info_impl.h
- core/coreobjects/src/callable_info_impl.cpp
- core/coreobjects/tests/test_callable_info.cpp
- docs/Antora/modules/knowledge_base/pages/property_system.adoc
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- regression/simulator/regression_simulator.cpp
- regression/tests/reg_p_test_channel.cpp
- regression/tests/reg_p_test_component.cpp
- regression/tests/reg_p_test_folder.cpp
- regression/tests/reg_p_test_serialization.cpp
- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- shared/libraries/config_protocol/include/config_protocol/config_server_component.h
- shared/libraries/config_protocol/src/config_protocol_server.cpp
- shared/libraries/config_protocol/tests/test_config_protocol_access_control.cpp
- shared/libraries/config_protocol/tests/test_config_protocol_device_locking.cpp
-  Add an option to mark functions and procedures as const
- Allow triggering of const function properties under locked device over native config protocol
>  Add an option to mark functions and procedures as const

- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- modules/tests/test_opendaq_device_modules/test_default_config.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
* Additionally allow the `"ProtocolVersion"` property to be populated from the module options JSON file.
> <TBBAS-1842> Remove redundant properties from native streaming config

- core/opendaq/reader/include/opendaq/multi_reader_impl.h
- core/opendaq/reader/include/opendaq/read_info.h
- core/opendaq/reader/src/multi_reader_impl.cpp
- core/opendaq/reader/tests/test_multi_reader.cpp
TBBAS-1780 - Multireader timeouts not working properly when the reader is created with builder from signals
Reason: listener has been set up for port after port was connected
TBBAS-1794 - Multi reader with timeout waits for data even if there's enough data available
Reason: if synchronization happened in conditional variable predicate, zero read is not happened after waiting on conditional variable
> TBBAS-1780, TBBAS-1794 MultiReader timeout fixes

- docs/Antora-specs/antora.yml
- docs/Antora/antora.yml
- docs/Antora/modules/getting_started/pages/quick_start_setting_up_cpp.adoc
- docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
- docs/Antora/modules/howto_guides/pages/howto_read_aligned_signals.adoc
- docs/version_injector.py
* Rename placeholder because it is shown in https://opendaq.github.io/
* Showing the version as `latest_dev_opendaq_version` is more correct than showing future version
> openDAQ versioning fixes

- shared/libraries/opcuatms/opcuatms/src/converters/unit_converter.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_fusion_device.cpp
OPC UA - Add missing namepaceUri field in EUInformationWithQuantity Struct and extend unit tests
Missing namespaceUri was hardcoded in struct converter. Value is now "http://[www.opcfoundation.org/UA/units/un/cefact](http://www.opcfoundation.org/UA/units/un/cefact)" taken from [here ](https://reference.opcfoundation.org/Core/Part8/v104/docs/5.6.3):
> OPC UA - Add missing namepaceUri field in EUInformationWithQuantity Struct

- modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
- modules/native_streaming_client_module/src/native_device_impl.cpp
- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
* Resolved issue with client-side modified DeviceInfo fields being lost after device update due to loadConfig and reconnection
* Fixed issue where signals newly added on the server during client-triggered loadConfig lack streaming sources on client side once the loadConfig completed
> <TBBAS-1892> Restore DeviceInfo fields after native device update

- examples/python/gui_demo/components/add_device_dialog.py
device.available_devices throws exception with older devices
> Fix crash in python GUI demo when adding a device based on older openDAQ

- docs/tests/test_modules.cpp
- external/native_streaming/CMakeLists.txt
- modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
- modules/native_streaming_server_module/tests/test_native_streaming_server_module.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/server_session_handler.h
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h
- shared/libraries/native_streaming_protocol/src/base_session_handler.cpp
- shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
- shared/libraries/native_streaming_protocol/src/server_session_handler.cpp
- shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
- shared/libraries/packet_streaming/include/packet_streaming/packet_streaming.h
- shared/libraries/packet_streaming/include/packet_streaming/packet_streaming_server.h
- shared/libraries/packet_streaming/src/packet_streaming.cpp
- shared/libraries/packet_streaming/src/packet_streaming_server.cpp
- shared/libraries/packet_streaming/tests/packet_transmission.cpp
- shared/libraries/packet_streaming/tests/test_packet_streaming.cpp
Related PR in libNative - https://github.com/openDAQ/libNativeStreaming/pull/18
Introduce an optional timeout for streaming packet writes:
* Add the "StreamingPacketSendTimeout" property to the native server for specifying the timeout value.
* Enable "PacketStreamingServer" to optionally add a timestamp to serialized openDAQ packets at "PacketBuffer" creation.
* Calculate the deadline for the start time point of the packet write operation using the serialized packet's timestamp and the specified timeout.
* Server resets the client connection if the deadline is exceeded.
> <TBBAS-1845> mitigate out-of-memory risk on server-side for native streaming

- external/native_streaming/CMakeLists.txt
- shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
Related PR - https://github.com/openDAQ/libNativeStreaming/pull/19
> <TBBAS-1843> Add timeout constraint for re-connection attempt in native

- CMakeBasePresets.json
- CMakeLists.txt
- core/opendaq/reader/tests/reader_common.h
- core/opendaq/reader/tests/test_multi_reader.cpp
- docs/tests/docs_test_helpers.h
- docs/tests/test_quick_start.cpp
- modules/tests/test_opendaq_device_modules/test_default_config.cpp
- modules/tests/test_opendaq_device_modules/test_helpers/test_helpers.h
- modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
- modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
- modules/tests/test_opendaq_device_modules/test_streaming.cpp
- modules/tests/test_opendaq_device_modules/test_subdevices.cpp
- modules/tests/test_opendaq_device_modules/test_websocket_modules.cpp
- modules/tests/test_ref_modules/test_ref_modules.cpp
- shared/libraries/config_protocol/tests/test_c2d_streaming.cpp
- shared/libraries/packet_streaming/tests/CMakeLists.txt
- shared/libraries/packet_streaming/tests/test_app.cpp
- shared/libraries/testutils/include/testutils/base_test_listener.h
- shared/libraries/testutils/include/testutils/testutils.h
- shared/libraries/testutils/src/CMakeLists.txt
- shared/libraries/testutils/src/base_test_listener.cpp
- shared/libraries/testutils/src/memcheck_listener.cpp
- shared/libraries/websocket_streaming/tests/CMakeLists.txt
- shared/libraries/websocket_streaming/tests/streaming_test_helpers.h
- shared/libraries/websocket_streaming/tests/test_app.cpp
* Introduces mechanism to skip "flaky" failing tests
* Makes majority of failing test listed in TBBAS-1735 skipped within regular CI test jobs
> Allow to disable flaky tests

- examples/python/gui_demo.py
- examples/python/gui_demo/app_context.py
- examples/python/gui_demo/components/add_config_dialog.py
- examples/python/gui_demo/components/add_device_dialog.py
- examples/python/gui_demo/components/attributes_dialog.py
- examples/python/gui_demo/components/dialog.py
- examples/python/gui_demo/components/edit_container_property.py
- examples/python/gui_demo/components/load_instance_config_dialog.py
- examples/python/gui_demo/components/metadata_dialog.py
- examples/python/gui_demo/components/metadata_fields_selector_dialog.py
- examples/python/gui_demo/components/properties_view.py
- examples/python/gui_demo/utils.py
This PR adds functionality to view **Metadata fields** of components' **properties**. It also includes some additional changes:
- Boolean properties could be flipped by double click
- Errors notification dialogs
- Various properties view UX improvements
> [TBBAS-1819] Python GUI: Property metadata view

- core/coreobjects/include/coreobjects/component_type_impl.h
- core/opendaq/modulemanager/include/opendaq/module_impl.h
- core/opendaq/opendaq/tests/CMakeLists.txt
- core/opendaq/opendaq/tests/test_module_callbacks.cpp
- core/opendaq/server/tests/test_server_type.cpp
- docs/tests/test_examples.cpp
- docs/tests/test_quick_start.cpp
- modules/ref_device_module/src/ref_device_impl.cpp
- modules/ref_device_module/src/ref_device_module_impl.cpp
- modules/ref_device_module/tests/test_ref_device_module.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
Automatically populate user config object before passing it to the module callbacks (`onCreateDevice`, `onCreateServer`...)
> Automatically populate default config in module implementation

- changelog/changelog_3.0.0-4.0.0.md
- core/coreobjects/include/coreobjects/core_event_args.h
- core/coreobjects/include/coreobjects/core_event_args_impl.h
- core/coretypes/include/coretypes/enumeration.h
- core/coretypes/src/type_manager_impl.cpp
- core/opendaq/component/include/opendaq/component.h
- core/opendaq/component/include/opendaq/component_impl.h
- core/opendaq/component/include/opendaq/component_status_container.h
- core/opendaq/component/include/opendaq/component_status_container_impl.h
- core/opendaq/component/include/opendaq/component_status_container_private.h
- core/opendaq/component/tests/test_component.cpp
- core/opendaq/component/tests/test_component_status_container.cpp
- core/opendaq/functionblock/include/opendaq/function_block.h
- core/opendaq/modulemanager/src/context_impl.cpp
- docs/Antora/modules/knowledge_base/pages/components.adoc
- docs/tests/test_components.cpp
- modules/ref_fb_module/include/ref_fb_module/scaling_fb_impl.h
- modules/ref_fb_module/src/classifier_fb_impl.cpp
- modules/ref_fb_module/src/fft_fb_impl.cpp
- modules/ref_fb_module/src/power_fb_impl.cpp
- modules/ref_fb_module/src/power_reader_fb_impl.cpp
- modules/ref_fb_module/src/renderer_fb_impl.cpp
- modules/ref_fb_module/src/scaling_fb_impl.cpp
- modules/ref_fb_module/src/statistics_fb_impl.cpp
- modules/ref_fb_module/src/struct_decoder_fb_impl.cpp
- modules/ref_fb_module/src/trigger_fb_impl.cpp
- modules/ref_fb_module/tests/test_fb_statistics.cpp
- modules/ref_fb_module/tests/test_fb_trigger.cpp
- modules/ref_fb_module/tests/test_ref_fb_module.cpp
- modules/tests/test_ref_modules/test_ref_modules.cpp
* Add Component status types to the Type Manager in `context_impl.cpp` ("Ok", "Warning", and "Error")
* Define `ComponentErrorState`
* Declare and define `initComponentErrorStateStatus`, `setComponentErrorStateStatus`, and `setComponentErrorStateStatusWithMessage` in `component_impl.h`
* Add `getStatusMessage` in `component_status_container.h`, and `addStatusWithMessage`, `setStatusWithMessage` in `component_status_container_private.h` , implement all three in `component_status_container_impl.h`, and make other appropriate changes wherever necessary
* Use `initComponentErrorStateStatus` and `setComponentErrorStateStatusWithMessage` in all reference Function Blocks
* Add appropriate tests and supplement existing ones
* Modify Doxygen and Antora docs
* Fix typos, and other minor issues, …
> Component status extension

- core/opendaq/opendaq/tests/test_core_events.cpp
- modules/tests/test_opendaq_device_modules/CMakeLists.txt
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h
Status message is currently not propagated to client, because "message" field is treated as status. This PR is a temporary workaround. I think that original issue is that parameters for status changed are set like this:
```
{
"StatusName": IEnumeration_StatusValue,
"Message": "some message"
}
const CoreEventArgsPtr args = createWithImplementation<ICoreEventArgs, CoreEventArgsImpl>(
CoreEventId::StatusChanged, Dict<IString, IBaseObject>({{name, value}, {"Message", message}}));
```
So the problem is that "StatusName" is the key. Probably it was designed like this so that multiple statuses can be reported. But this does not work with messages, as we can have only one message. The full solution would be something like this:
```
{
"StatusName1": {
"Value":  IEnumeration_StatusValue
"Message": …
```
> Fix status messages not propagated via native protocol

- core/opendaq/component/include/opendaq/component_status_container_impl.h
The current implementation returns an internal dictionary of statuses, which is not thread-safe and potentially dangerous because one thread can update the status. At the same time, the other reads the statuses via the dictionary, which is not under lock.
> Return a copy of internal dictionary of current statuses instead of original

- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- shared/libraries/config_protocol/include/config_protocol/config_client_component_impl.h
Component status was not a part of remote-update on configuration client objects.
Slightly off-topic, I don't like the way we have deserialization/update implemented on remote objects. Every change applied on openDAQ components must be applied to configuration client remote objects. I prefer the remote update to be implemented on the components themselves.
> Properly set component status on reconnect

- core/opendaq/opendaq/include/opendaq/instance_impl.h
- core/opendaq/opendaq/src/instance_impl.cpp
- core/opendaq/opendaq/tests/test_instance.cpp
- `rootDevice.remove()` is now called on instance destruction.
- openDAQ components can hook onto the `onRemoved()` that will be called when the openDAQ program terminates.
> Remove root device on instance destruction

- .github/workflows/deploy.yml
Enables uploading Python Wheels to S3 from branches other than `refs/heads/main` to be more in line with other files (nuget package, docs, etc.) being uploaded (e.g. via `workflow_dispatch`) for `deploy.yml` workflow.
Noticed the files were missing when I tried deploying files to AWS S3 for "manual" update of  https://docs.opendaq.com to `3.10.2`.
> Upload Python Wheels to S3 even if not `refs/heads/main`

- examples/python/gui_demo/components/attributes_dialog.py
This fixes the issue of attributes not being editable in Python GUI Demo Application
* This works, because there is an unexpected `.` at the beginning of `sel`
* Because the code that handles the logic for this action was already there I'm assuming this either:
* Never worked as intended
* Stopped working due to to updates in either Python or tkinter versions (most likely the latter)
* Tested using:
* `Python 3.12.8`
* `tkinter 8.6`
* `opendaq-3.11.0+301c940-cp312-cp312-win_amd64.whl`
* Not sure what else could be relevant
* My other worry is that `utils.treeview_get_first_selection` function has the possibility of returning `None`, and, in turn, this generating an error, but I'm guessing `None` was intended for other cases where this function is used
> Make attributes editable in Python GUI Demo Application

- core/opendaq/component/include/opendaq/component_impl.h
- core/opendaq/component/tests/test_component.cpp
- modules/tests/test_opendaq_device_modules/test_native_streaming_modules.cpp
The "Name" attribute was not serialized when equal to the local ID. This caused Native streaming signals to have mangled names, as they would be set to be the same as the client-side signal local IDs (eg. `"mydev*FB*FB1*Sig*Signal1"`)
> Serialize component name when equal to localID

- .github/pull_request_template.md
- README.md
- changelog/changelog_1.0.0-2.0.0.md
- changelog/changelog_2.0.0-3.0.0.md
- changelog/changelog_3.0.0-4.0.0.md
- core/opendaq/component/include/opendaq/component_impl.h
- core/opendaq/component/include/opendaq/component_status_container_impl.h
- core/opendaq/component/tests/test_component.cpp
- modules/ref_fb_module/include/ref_fb_module/renderer_fb_impl.h
- modules/ref_fb_module/src/classifier_fb_impl.cpp
- modules/ref_fb_module/src/fft_fb_impl.cpp
- modules/ref_fb_module/src/power_fb_impl.cpp
- modules/ref_fb_module/src/power_reader_fb_impl.cpp
- modules/ref_fb_module/src/renderer_fb_impl.cpp
- modules/ref_fb_module/src/scaling_fb_impl.cpp
- modules/ref_fb_module/src/statistics_fb_impl.cpp
- modules/ref_fb_module/src/struct_decoder_fb_impl.cpp
- modules/ref_fb_module/src/trigger_fb_impl.cpp
- modules/ref_fb_module/tests/test_fb_power_reader.cpp
- modules/ref_fb_module/tests/test_fb_statistics.cpp
- modules/ref_fb_module/tests/test_fb_trigger.cpp
- modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
- modules/tests/test_ref_modules/test_ref_modules.cpp
Component status fixes:
* Streamline naming for Component Status building blocks:
* `ComponentErrorStateStatus` to `ComponentStatus` (all variable names)
* `ComponentErrorState` to `ComponentStatus` (enum)
* Equip all existing Function Block implementations  with additional `setComponentStatus` calls, setting the Component Status back to `ComponentStatus::Ok`
* Avoid redundant code in Function Block implementations and improve logging:
* `LOG_` (`W`/`E`/`I` for Warning/Error/Ok) on each `setComponentStatusWithMessage`
* Delete all "manual" `LOG_` calls in Function Block implementations adjacent/related to `setComponentStatus`/`setComponentStatusWithMessage`
* Improve Component Status messages (and thereby log messages) in reference Function Blocks with additional info wherever possible
* …
> Component status fixes

- bindings/dotnet/openDAQ.Net/README.md
- bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/openDAQ.Net.CI.Test.csproj
- bindings/dotnet/openDAQ.Net/openDAQ.Net.NuGet.Test/openDAQ.Net.NuGet.Test.csproj
- bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/openDAQ.Net.Test.csproj
- bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coretypes/OpenDaqException.cs
- bindings/dotnet/openDAQ.Net/openDAQ.Net/media/README.md
- bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
.NET 6.0 has had its end-of-support in November 2024. Switched to the most recent runtime with long-term-support .NET 8.0.
> [TBBAS-2050] .NET Bindings - Bump-up to .NET 8.0

- examples/CMakeLists.txt
- examples/cpp/CMakeLists.txt
- examples/cpp/reconnection_example/CMakeLists.txt
- examples/cpp/reconnection_example/reconnection.cpp
- examples/cpp/reconnection_example/reconnection_v3_10.cpp
Adds examples highlighting how disconnection/reconnection can be detected on the 3.10 release, as well as on versions newer than 3.11.
> Add disconnection/reconnection detection examples

- modules/ref_fb_module/src/renderer_fb_impl.cpp
I think this should fix [TBBAS-2070] as well (must be tested to confirm)
> Initialize `futureComponentStatus` and `futureComponentMessage` in `renderer_fb_impl.cpp`, thereby preventing unwarranted crashes

- examples/python/gui_demo.py
- examples/python/gui_demo/app_context.py
Adds a command line option to specify an additional module load path when starting the Python GUI application
> Add Python app option to load additional module paths.

- core/coreobjects/include/coreobjects/property_object_impl.h
- shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
> Fix getPropertySelectionValue was returning the old value

- docs/Antora-specs/antora.yml
- docs/Antora/antora.yml
- opendaq_version_bump.py
Allow for conversion between development and release version via `opendaq_version_bump.py` script and vice versa
* Always write `MAJOR.MINOR.PATCH` to `opendaq_version` file
* Write `MAJOR.MINOR` to `docs/Antora/antora.yml` and `docs/Antora-specs/antora.yml` in case of release
* Write `dev` to `docs/Antora/antora.yml` and `docs/Antora-specs/antora.yml` in case of development (latest main)
* Rename version to `dev` in Antora
In terminal use:
```shell
python opendaq_version_bump.py
```
from openDAQ root directory and follow the onscreen instructions to bump the version and select development/release mode.
Example terminal output when converting from `3.11.0`, `dev` to `3.12.0`, `release`:
```
Current version (`MAJOR.MINOR.PATCH`): `3.11.0`
Current Antora version: `dev`
Bump for release or …
```
> Allow for conversion between development and release version

- modules/CMakeLists.txt
* Restore CMake compile definitions accidentally removed within merge commit
> Fix CMake compile definitions for simulator build

- CMakeLists.txt
- cmake/openDAQConfig.cmake.in
- cmake/openDAQUtils.cmake
Standard example openDAQ modules make use of non-installed openDAQ cmake utilities. This PR adds said cmake utilities to the installed openDAQ package.
The files DaqUtils.cmake, DaqInternal.cmake, as well as the input templates for version files have been added as targets for openDAQ installation. 
Module examples such as the [Simple FB Module](https://github.com/openDAQ/SimpleFBModule) and [Simple Device Module](https://github.com/openDAQ/SimpleDeviceModule) as of now fail on CMake configure when using an installed version of openDAQ due to the missing cmake utilities.
> Install missing CMake utilities

- core/coretypes/include/coretypes/number_impl.h
- core/coretypes/include/coretypes/ordinalobject_impl.h
- core/coretypes/tests/test_integer.cpp
Coretype INumber queryInterface & borrow interface optimization
Optimizes queryInterface and borrowInterface methods for number core types, such as integer and float.
> Optimize coretype number casting

- core/opendaq/logger/tests/test_logger_component.cpp
- core/opendaq/modulemanager/src/icmp_ping.cpp
- core/opendaq/modulemanager/tests/module_manager_test.cpp
- core/opendaq/modulemanager/tests/test_module_manager_internals.cpp
- core/opendaq/reader/src/multi_reader_impl.cpp
- core/opendaq/reader/tests/reader_common.h
- core/opendaq/scheduler/tests/test_scheduler.cpp
- core/opendaq/scheduler/tests/test_scheduler.h
- core/opendaq/scheduler/tests/test_scheduler_internals.cpp
- examples/cpp/reader_timeouts_example/reader_timeouts_example.cpp
- modules/ref_device_module/include/ref_device_module/ref_device_impl.h
- modules/ref_device_module/src/ref_can_channel_impl.cpp
- modules/ref_fb_module/include/ref_fb_module/renderer_fb_impl.h
- modules/ref_fb_module/tests/test_ref_fb_module.cpp
- modules/tests/test_opendaq_device_modules/test_helpers/test_helpers.h
- modules/tests/test_ref_modules/test_ref_modules.cpp
- modules/tests/test_ws_siggen_integration/test_websocket_siggen.cpp
- shared/libraries/config_protocol/include/config_protocol/config_protocol_streaming_producer.h
- shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
- shared/libraries/opcua/opcuaclient/include/opcuaclient/opcuaclient.h
- shared/libraries/opcua/opcuaclient/tests/include/opcuaservertesthelper.h
- shared/libraries/signal_generator/include/signal_generator/signal_generator.h
- shared/libraries/utils/tests/test_thread_ex.cpp
- shared/libraries/utils/tests/test_timer_thread.cpp
- shared/libraries/websocket_streaming/include/websocket_streaming/async_packet_reader.h
- shared/libraries/websocket_streaming/include/websocket_streaming/streaming_client.h
Fixed "unknown std::chrono namespace" issue introduced in VS2022 17.13.0
Microsoft changed an internal header, so the `chrono` header has to be included directly when `std::chrono` is in use (no longer included in `thread` header). 
Added `#include <chrono>` wherever there was `#include <thread>` and use of `std::chrono`. 
Affected directories: `./core/`, `./examples/`, `./modules/`, `./shared/libraries/`. 
Not all files containing `#include <thread>` are affected. 
Instead of:
`#include <thread>`
Do:
`#include <chrono>`
`#include <thread>`
n/a
> Fixed "unknown std::chrono namespace" issue introduced in VS2022 17.13.0

- modules/ref_fb_module/src/renderer_fb_impl.cpp
Two new resolution options have been added to the renderer function block: 1920x1080 and 2560x1440.
```cpp
auto instance = Instance();
auto fb = instance.addFunctionBlock("RefFBModuleRenderer");
fb.setPropertyValue("Resolution", 4);
```
> Add additional resolution options to renderer

- changelog/changelog_3.10-3.20.md
- core/opendaq/device/include/opendaq/device_info_impl.h
- core/opendaq/device/tests/test_device_info.cpp
- core/opendaq/modulemanager/src/module_manager_impl.cpp
- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- modules/opcua_client_module/src/opcua_client_module_impl.cpp
- modules/websocket_streaming_client_module/src/websocket_streaming_client_module_impl.cpp
- shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
- shared/libraries/config_protocol/tests/test_utils.h
- shared/libraries/opcuatms/opcuatms_client/src/tms_client.cpp
- The `IDeviceInfoConfig::setName` method now also changes the device's name instead of changing an internal, unreadable value once owner is assigned.
- The `IDeviceInfoConfig` setters no longer have protected access to read-only properties after owner is set.
The `IDeviceInfoConfig::setName` method was previously only useable when creating a DeviceInfo object meant for discovery. If an owner of the device info is assigned (which happens when the info object is obtained via `IDevice::getInfo`), the name of the info object is synced with that of the device. As `IDeviceInfoConfig::setName` previously only modified an internal variable, the function had no effect. With this change, the method now also modified the owner device's name (if the attribute is not locked).
Secondly, the …
> Device info `setName` changed device name + setting owner prevents writing of read-only values

- shared/libraries/discovery/include/daq_discovery/mdnsdiscovery_client.h
RFC 6762 §5.4 states that a server can respond to an mDNS unicast query with a multicast response, which was not handled in the OpenDAQ wrapper for mDNS. As a result, OpenDAQ could not discover devices using the Avahi server.
This fix resolves the issue by sending the request not only to the network interfaces but also to mDNS itself, allowing it to receive the response correctly.
(Individual high-level changes)
- Add Python GUI Demo functionality
- Rename a function
- ...
None
None
None
None
> Support  handling Query Multicast in mDNS

- modules/ref_device_module/src/ref_device_impl.cpp
Bounds property to min/max values
Channel numbers now could be only between 1 and 4096
> TBBAS-2071 Setting Number of Channels for Reference Device

- core/coreobjects/include/coreobjects/permission_manager_impl.h
- core/coreobjects/include/coreobjects/permissions_builder_impl.h
- core/coreobjects/include/coreobjects/permissions_impl.h
- core/coreobjects/include/coreobjects/property_impl.h
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/src/permission_manager_impl.cpp
- core/coreobjects/src/permissions_builder_impl.cpp
- core/coreobjects/src/permissions_impl.cpp
- core/opendaq/component/include/opendaq/component_impl.h
Set of permission manager optimizations that reduce the number of Dictionary object creations on `Property`/`PropertyObject` construction.
- Define static permission objects for default initializations of the permission managers of `PropertyObject`, `Property`, and Component
- Replace `PermissionBuilder` dictionaries with `std::map`
- Only create `PermissionManager` on `Property` creation when creating an object-type `Property`
> Permission manager optimizations

- docs/tests/test_modules.cpp
- modules/native_streaming_server_module/include/native_streaming_server_module/native_streaming_server_impl.h
- modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
- modules/native_streaming_server_module/tests/test_native_streaming_server_module.cpp
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/base_session_handler.h
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_server_handler.h
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h
- shared/libraries/native_streaming_protocol/src/base_session_handler.cpp
- shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
- shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
- shared/libraries/native_streaming_protocol/tests/test_streaming_protocol.cpp
- shared/libraries/packet_streaming/include/packet_streaming/packet_streaming_server.h
- shared/libraries/packet_streaming/src/packet_streaming_server.cpp
Native streaming packet transmitting performance optimizations
Optimizes native streaming packet transmitting by:
* merging transport header write task and packet buffer header write task into single task with common contiguous buffer
* writing all available packet buffers per each connected client within a single transport operation
None
None
None
None
> Native streaming performance optimization

- CMakeLists.txt
- core/coreobjects/src/CMakeLists.txt
Move OPENDAQ_ENABLE_ACCESS_CONTROL flag to coreobjects
> Move OPENDAQ_ENABLE_ACCESS_CONTROL flag to coreobjects

- changelog/changelog_3.10-3.20.md
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/tests/test_property_object.cpp
- core/opendaq/scheduler/tests/test_task_internals.cpp
- shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
- shared/libraries/config_protocol/tests/test_utils.cpp
- shared/libraries/opcua/opcuaclient/tests/src/test_opcuaasyncexecthread.cpp
Fixes error when accessing selection property values using "dot" notation (eg. `getPropertySelectionValue("child.val")`).
```cpp
auto child = PropertyObject();
child.addProperty(SelectionProperty("foo", List<IString>("a", "b"), 0));
auto parent = PropertyObject();
parent.addProperty(ObjectProperty("child", child))
// Now no longer throws and exception
auto val = parent.getPropertySelectionValue("child.foo");
```
> Fix selection value dot access

- changelog/changelog_3.10-3.20.md
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- shared/libraries/config_protocol/include/config_protocol/config_client_function_block_impl.h
- shared/libraries/config_protocol/include/config_protocol/config_protocol.h
- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- shared/libraries/config_protocol/include/config_protocol/config_server_component.h
- shared/libraries/config_protocol/include/config_protocol/config_server_device.h
- shared/libraries/config_protocol/src/config_protocol_client.cpp
- shared/libraries/config_protocol/src/config_protocol_server.cpp
- shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
- shared/libraries/config_protocol/tests/test_utils.cpp
- shared/libraries/config_protocol/tests/test_utils.h
Adds new Native Configuration Protocol RPCs for handling sub-function blocks (function blocks that are children of other FBs).
Previously, adding of nested function blocks was possible only locally, as the Native configuration protocol was missing definitions for remote procedure calls that allow for said action. This change enables adding, removing, and checking for available function blocks that can be added as a child of another FB on remote devices using the Native protocol.
This change requires the latest openDAQ version on both the server and client side.
> Add RPCs for handling nested function blocks

- bindings/dotnet/openDAQ.Net/openDAQ.Net/core/opendaq/OpenDAQFactory.cs
- bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
- bindings/dotnet/openDAQ.Net/openDAQ.Net/opendaq.cd
- bindings/dotnet/openDAQ.Net/openDAQDemo.Net/frmMain.cs
Using the .NET Bindings (NuGet package) in Linux gives several "cannot open shared object file: No such file or directory" errors when creating an Instance object.
When creating a .NET project, adding the NuGet package, and then directly creating an Instance object, running the binary fails, stating that it cannot find `libopendaq-64-3.so` (in various directories).
It does not state it for the directory where it physically exists though (because it really tried to load it from there).
Somehow the two dependencies `libcoretypes-64-3.so` and `libcoreobjects-64-3-so` cannot be loaded (only when the Linux environment variable for the search-path is set).
This fix just gets the SDK-Version for each library in the static constructor of the `OpenDaqFactory` so that all libraries will be loaded …
> .NET Bindings - Fix loading `libopendaq-64-3.so` in Linux

- changelog/changelog_3.10-3.20.md
- examples/python/gui_demo/components/attributes_dialog.py
- examples/python/gui_demo/components/data_descriptor_treeview.py
- examples/python/gui_demo/components/device_info_dialog.py
- examples/python/gui_demo/components/generic_attributes_treeview.py
- examples/python/gui_demo/components/input_port_row_view.py
- examples/python/gui_demo/components/metadata_fields_selector_dialog.py
Improve Python GUI app: attributes dialog update, device info via generic properties treeview, metadata fields fix
- Attributes dialog update
- Move all logic for topmost TreeView in `attributes_dialog.py` to `generic_attributes_treeview.py`
- Use `generic_properties_treeview.py` for `additional_tree_frame` if `daq.IDevice.can_cast_from(node)` allowing for modifications
- Introduce `data_descriptor_treeview.py` and use it for `additional_tree_frame` if `daq.ISignal.can_cast_from(node)` (it's read only)
- Set parent for `simpledialog.ask...` to prevent pop-ups under current window
- Enable nested property objects in device info dialog via generic properties treeview
- Fix metadata fields not showing up
- Fix crash if no `related_signals`
- Fix typos, minor fixes
> Python GUI app: attributes dialog, changeable device info, metadata fields fix

- changelog/changelog_3.10-3.20.md
- core/opendaq/modulemanager/include/opendaq/module_manager_impl.h
- core/opendaq/modulemanager/src/module_manager_impl.cpp
- core/opendaq/modulemanager/tests/module_manager_test.cpp
- core/opendaq/opendaq/src/instance_builder_impl.cpp
Add timeout on to re-scan after for available devices after 5s in the module manager call `createDevice`.
The openDAQ module manager scans for available devices before attempting to create a device. This is done to gather all device capabilities for configuration/streaming, and to allow adding a device via the connection string format "daq://Manufacturer_SerialNumber".
This was only done if `getAvailableDevices` has not been called at all in the lifetime of the module manager. This PR changes said behaviour by introducing a 5s  timeout post `getAvailableDevices`. If a device is created after said timeout, the module manager now re-scans before creating the device.
When re-booting a device with manufacturer "openDAQ" and serial "SN123",  the following code snippet previously never …
> Add scan timeout in `createDevice`

- core/coretypes/include/coretypes/exceptions.h
Fixing compile issue by using ##__VA_ARGS__ instead of __VA_ARGS__ in the macros DAQ_THROW_EXCEPTION (introduced in [#721](https://github.com/openDAQ/openDAQ/pull/721)) to remove comma if arguments are empty.
> Fix compiling issue because of  __VA_ARGS__ in macros DAQ_THROW_EXCEPTION

- examples/cpp/client_discovery/client_discovery.cpp
Fix a comment in `client_discovery.cpp` that has been obsolete since 5eb942820395b6b7b769b330ba05d86641e92703.
> Fix comment in `client_discovery.cpp`

- changelog/changelog_3.10-3.20.md
- core/corecontainers/include/coretypes/listobject_impl.h
- core/corecontainers/src/dictobject_impl.cpp
- core/corecontainers/src/listobject_impl.cpp
- core/coreobjects/src/user_impl.cpp
- core/coreobjects/tests/test_property.cpp
- core/coreobjects/tests/test_property_object_class.cpp
- core/coretypes/include/coretypes/common.h
- core/coretypes/include/coretypes/json_serializer.h
- core/coretypes/include/coretypes/json_serializer_factory.h
- core/coretypes/include/coretypes/json_serializer_impl.h
- core/coretypes/include/coretypes/serializer.h
- core/coretypes/include/coretypes/serializer_ptr.h
- core/coretypes/src/json_serializer_impl.cpp
- core/coretypes/src/util.cpp
- core/coretypes/tests/test_dictobject.cpp
- core/coretypes/tests/test_intfid.cpp
- core/coretypes/tests/test_json_serializer.cpp
- core/coretypes/tests/test_listobject.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- shared/libraries/config_protocol/include/config_protocol/config_protocol.h
- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- shared/libraries/config_protocol/src/config_protocol_client.cpp
- Fixes list/dictionary deserialization not containing key/value/item interface IDs.
- Introduces serializer versioning; openDAQ list objects are now serialized as objects instead of JSON arrays.
List and Dictionary objects in openDAQ store a key/value/list interface ID internally that can be used to retrieve the expected interface of stored objects. This is set on object construction if specified as a constructor parameter.
However, the serialization/deserialization of objects did not store/restore said ID, resulting in deserialized objects losing said information. As the openDAQ Native Configuration protocol uses the serialization mechanisms, client list/dictionary objects did not retain the interface ID variables.
This PR addresses this issue by serializing said values. It, however, …
> Add element IntfID to list/dict serialization + Serialization versioning

- changelog/changelog_3.10-3.20.md
- core/opendaq/functionblock/include/opendaq/function_block_impl.h
Fixed an issue with restoring connection signals to dynamic input ports of a function block while loading the configuration when the name of the new input does not match the old one.
The issue was in the logic of the method `FunctionBlockImpl<TInterface, Interfaces...>::onUpdatableUpdateEnd`. If a signal did not find the expected input port, it searched for an unconnected input port. However, for some reason, the connection to another input port was not registered in `ComponentUpdateContext`, causing the input port to be unaware of which signal to connect to.
This PR resolves the issue by ensuring that the connection to the correct input port is properly registered in `ComponentUpdateContext`, allowing signals to be restored correctly when loading the configuration.
> [TBBAS-2157] Function blocks with dynamic input ports don't get correctly loaded if input port names don't match name

- core/opendaq/logger/src/logger_thread_pool_impl.cpp
- core/opendaq/modulemanager/src/module_manager_impl.cpp
- core/opendaq/utility/include/opendaq/thread_name.h
- core/opendaq/utility/src/CMakeLists.txt
- core/opendaq/utility/src/thread_name.cpp
- modules/native_streaming_client_module/src/CMakeLists.txt
- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- modules/native_streaming_server_module/src/CMakeLists.txt
- modules/native_streaming_server_module/src/native_streaming_server_impl.cpp
- modules/ref_device_module/src/ref_device_impl.cpp
- modules/ref_fb_module/src/renderer_fb_impl.cpp
- shared/libraries/config_protocol/src/config_protocol_streaming_producer.cpp
- shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
- shared/libraries/opcua/opcuaclient/src/opcuaclient.cpp
- shared/libraries/utils/include/opendaq/utils/timer_thread.h
- shared/libraries/utils/src/timer_thread.cpp
- shared/libraries/utils/tests/test_timer_thread.cpp
Adds `daqNameThread`, which sets a thread's name. This is helpful during debugging and resource monitoring. It also sets the name of some threads.
Debuggers usually have a "threads" view that displays a list of threads. However, it can be challenging to identify them. Most debuggers and resource monitoring tools can also print the thread's name. `daqNameThread` must be called within the context of the target thread.
In C++ use:
```cpp
#include <opendaq/thread_name>
std::thread([] {
// ...
daqNameThread("CustomThread");
// ...
}
```
```diff
+ daqNameThread(const char* name)
```
> Set thread names

- core/coretypes/include/coretypes/ctutils.h
Fix ctutils library compilation yielding a Warning for lack of nullptr initialization
- Added cleaner pointer initialization
> [openDAQ] Fix ctutils initialization yielding warning as error

- changelog/changelog_3.10-3.20.md
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/tests/test_property_object.cpp
When clearing a property value, the `PropertyValueArgs` object obtained in the `onWrite` callback now contains the default value instead of an empty ptr.
When a `onWrite` event was previously triggered by a `clearPropertyValue` call, the `args.getValue()` method would return an empty ptr. Users needed to always check for `args.getPropertyEventType()` being `Clear` to know whether or not the args contain a newly written value.
With this change, the same code can be used whether the event is `Clear` or `Write`, as the args value on `Clear` will contain the default property value.
```cpp
propObj.getOnPropertyValueWrite("FloatProperty") +=
[](PropertyObjectPtr& /*sender*/, PropertyValueEventArgsPtr& args)
{
// Works regardless of PropertyEventType
valueChanged(args.getValue());
};
```
> Set default value as args newValue on clear instead of empty ptr

- core/coretypes/include/coretypes/procedure_impl.h
Initialized IProcedure objects to default value: `nullptr`.
Uninitialized objects cause potential use-before-init errors for certain compilers.
> Bugfix: Initialize IProcedure objects to nullptr

- changelog/changelog_3.10-3.20.md
- shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_device.cpp
Treat duplicate OPC-UA properties, with names that differ only in case, as warnings instead of fatal errors.
During the in-person workshop in Darmstadt, debugging revealed that devices using older openDAQ SDK versions may publish the "Location" and "UserName" twice, with the published nodes differing only in case. Those two properties are explicitly handled in openDAQ  to map to the lowercase "location" and "userName" property of a Device/DeviceInfo. This results in an "AlreadyExistsException" being thrown on connect.
This PR changes the TMS client to treat this condition as a warning instead of a fatal error. A message like this is logged to the logger:
"OPC UA property "location" already exists. The duplicate property will be ignored."
This allows the current SDK to connect to OPC-UA …
> OPC-UA client: warn and ignore duplicate properties

- bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqGettingStartedGuidesTests.cs
- bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/openDAQ.Net.Test.csproj
- bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coreobjects/CoreObjectsFactory.cs
- bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coretypes/CoreTypesFactory.cs
- bindings/dotnet/openDAQ.Net/openDAQ.Net/core/opendaq/OpenDAQFactory.cs
- bindings/dotnet/openDAQ.Net/openDAQ.Net/openDAQ.Net.csproj
- docs/Antora/modules/getting_started/pages/quick_start_application.adoc
- docs/Antora/modules/getting_started/pages/quick_start_setting_up_csharp.adoc
- examples/dotnet/quick_start/quick_start_simulator.cs
General update of the quick-start documentation for usage of .NET on Windows and Linux.
General alignment of the .NET examples to the C++ and Python examples.
Now the .NET examples and commands can be run from both, Windows and Linux console (tested with WSL/Windows Subsystem for Linux).
There is also a small fix regarding the preloading of openDAQ libraries under Linux (in the static constructor of the factories) so that the dependencies can be found.
Also contains fix for `WORKING_DIRECTORY` of CMake `add_test(...)` applied to RC 3.20.
n/a
n/a
n/a
n/a
> [TBBAS-1957] .NET bindings usage guide on Linux

- .github/workflows/reusable_nuget_creation_and_test.yml
Fix version extraction in `reusable_nuget_creation_and_test.yml` by accounting for suffix (rc, dev)
> Fix version extraction in `reusable_nuget_creation_and_test.yml`

- core/coreobjects/include/coreobjects/property_object.h
- docs/Antora/modules/getting_started/pages/quick_start_application.adoc
- docs/Antora/modules/getting_started/pages/quick_start_setting_up_cpp.adoc
- docs/Antora/modules/getting_started/pages/quick_start_setting_up_csharp.adoc
- docs/Antora/modules/getting_started/pages/quick_start_setting_up_python.adoc
- docs/Antora/modules/glossary/pages/glossary.adoc
- docs/Antora/modules/howto_guides/nav-howto-guides.adoc
- docs/Antora/modules/howto_guides/pages/howto.adoc
- docs/Antora/modules/howto_guides/pages/howto_access_control_connect.adoc
- docs/Antora/modules/howto_guides/pages/howto_access_control_introduction.adoc
- docs/Antora/modules/howto_guides/pages/howto_access_control_protected_object.adoc
- docs/Antora/modules/howto_guides/pages/howto_access_control_user_list.adoc
- docs/Antora/modules/howto_guides/pages/howto_add_function_block.adoc
- docs/Antora/modules/howto_guides/pages/howto_configure_function_block.adoc
- docs/Antora/modules/howto_guides/pages/howto_configure_instance.adoc
- docs/Antora/modules/howto_guides/pages/howto_configure_instance_providers.adoc
- docs/Antora/modules/howto_guides/pages/howto_configure_streaming.adoc
- docs/Antora/modules/howto_guides/pages/howto_connect_to_device.adoc
- docs/Antora/modules/howto_guides/pages/howto_measure_single_value.adoc
- docs/Antora/modules/howto_guides/pages/howto_read_aligned_signals.adoc
- docs/Antora/modules/howto_guides/pages/howto_read_last_n_samples.adoc
- docs/Antora/modules/howto_guides/pages/howto_read_with_domain.adoc
- docs/Antora/modules/howto_guides/pages/howto_read_with_timeouts.adoc
- docs/Antora/modules/howto_guides/pages/howto_read_with_timestamps.adoc
- docs/Antora/modules/howto_guides/pages/howto_save_load_configuration.adoc
- docs/Antora/modules/howto_guides/pages/howto_vbox_simulator.adoc
- docs/Antora/modules/knowledge_base/nav-knowledge_base.adoc
- docs/Antora/modules/knowledge_base/pages/modules.adoc
Introduces the first set of Antora docs improvements
- Clean up links in Antora docs
- Move "Save and load Configuration" how-to guide up
- Fix "OPC-UA" to "OPC UA"
- Move some articles to a higher level in navigation
- Version fix:
- Use placeholder `<version>` (`dev` is erroneously shown in development mode)
-  Use placeholder `<short-sha>`
- Fix DoxyGen comment (unrelated)
- Shorten `quick_start_application.adoc` somewhat, minor fixes
- Fix indentation
- Add learning outcomes to Antora docs
- Add `daq.nd://` explainer and fix some typos
> Initial set of Antora docs improvements

- modules/new_websocket_streaming_server_module/include/httpparser/httprequestparser.h
- modules/new_websocket_streaming_server_module/src/CMakeLists.txt
Partially addresses problems encountered while building the new High-Performance WebSocket Streaming Server Module.
* Fix `Boost::asio` in CMake
* Fix `strcasecmp`
> Partial High-Performance WebSocket Streaming Server Module fixes

- changelog/changelog_3.10-3.20.md
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/tests/test_property_object.cpp
- core/opendaq/functionblock/src/function_block_wrapper_impl.cpp
- shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
Extend `IPropertyObject::hasProperty()` to accept nested property lookup via "dot" notation.
```cpp
auto propObj = PropertyObject();
auto childObj = PropertyObject();
childObj.addProperty(StringProperty("foo", "bar"));
const auto childProp = ObjectProperty("child", childObj );
propObj.addProperty(childProp);
// returns `true`
bool hasProp = propObj.hasProperty("child.foo");
```
> `hasProperty` extension for nested property object paths

- changelog/changelog_3.10-3.20.md
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/opendaq/opendaq/mocks/mock_physical_device.cpp
- core/opendaq/opendaq/tests/test_instance.cpp
Fixing restoring struct fields while loading configuration
type manager was missed in reading object in `setPropertyFromSerialized`
None
None
None
> Fixing restoring struct fields while loading configuration

- changelog/changelog_3.10-3.20.md
- core/coretypes/include/coretypes/struct_impl.h
- core/coretypes/src/enumeration_impl.cpp
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- shared/libraries/config_protocol/src/config_protocol_client.cpp
Fixing calling remote function with enumeration inside
While remote calling of function, the context was not provided which causes the problem for returning result, which uses type manager
None
None
None
> Fixing remote calling function with enumeration

- core/coretypes/include/coretypes/ctutils.h
Optimization of the `wrapHandler` method
The `wrapHandler` method does not properly forward parameters. It does not use rvalue semantics on parameters, creating unnecessary copies of them.
> Properly forward parameters in wrapHandler

- changelog/changelog_3.10-3.20.md
- modules/tests/test_opendaq_device_modules/test_native_device_modules.cpp
- shared/libraries/config_protocol/include/config_protocol/config_protocol.h
- shared/libraries/config_protocol/src/config_protocol_client.cpp
Increases config protocol version number to 14 and fixes wrong version number for Recorder RPCs
> Fix native config protocol versioning

- modules/new_websocket_streaming_server_module/src/CMakeLists.txt
There is no boost::endian library when boost libraries are installed via package manager on ubuntu
Remove implicit library dependency on boost endian. boost::headers should be enough.
> Remove Boost::endian dep

- changelog/changelog_3.10-3.20.md
- core/coreobjects/include/coreobjects/property_impl.h
- core/opendaq/signal/include/opendaq/input_port_impl.h
- core/opendaq/signal/tests/test_input_port.cpp
- shared/libraries/config_protocol/tests/test_c2d_streaming.cpp
Adds missing input port notification sent to previously connected signal when it is replaced by new connected signal.
- Stabilizes client-to-device streaming tests by fixing issues with input port to signal notifications and test environment
> Fix input port to signal notification

- changelog/changelog_3.10-3.20.md
- core/coreobjects/include/coreobjects/property_builder_impl.h
- core/coreobjects/include/coreobjects/property_impl.h
- core/coreobjects/include/coreobjects/property_object_impl.h
Small refactor/fixing of child object cloning logic. Ensure thread safety on core event enabling.
- When adding object-type properties, the default value of the property is first stored, then cloned and overridden in the property.
- `setPath` and `setCoreEventTrigger` are now under a lock.
- Removed default permission manager from property implementations.
> Refactor child object cloning + thread safety

- core/coretypes/include/coretypes/ctutils.h
- core/coretypes/include/coretypes/validation.h
Moves the new return macros from validation.h to cutils.h to prevent build issues when `OPENDAQ_ENABLE_PARAMETER_VALIDATION` is off.
> Move return macros to cutils.h

- bindings/python/opendaq/generated/device/py_device.cpp
- changelog/changelog_3.20-3.30.md
- examples/cpp/quick_start/quick_start_empty.cpp
- examples/python/gui_demo/components/block_view.py
Enable Device operation mode switching in Python GUI Demo Application.
- Add `operation_mode` getter to Python bindings
- Add logic to handle operation mode switching though Python GUI Demo App
In Python GUI Demo App use:
> Device operation mode switching in Python GUI Demo Application

- changelog/changelog_3.10-3.20.md
- core/opendaq/opendaq/mocks/advanced_components_setup_utils.cpp
- core/opendaq/opendaq/src/instance_impl.cpp
- shared/libraries/config_protocol/src/config_protocol_client.cpp
- shared/libraries/config_protocol/tests/test_config_protocol_integration.cpp
Fix issue with domain signals missing for hidden signals of device connected via native configuration protocol
Previously, domain signals were not assigned for hidden signals when connected via the native configuration protocol. 
The configuration client handled domain assignment (for signals) and connected signal resolution (for input ports) only for visible components, now it does so also for hidden ones.
> Fix hidden components deserialization

- shared/libraries/discovery/src/daq_discovery_client.cpp
For devices using SDK versions older than 3.10.3, the displayed SDK version was incorrectly showing the client’s version. Since the actual version can’t be retrieved, we now indicate it as "<3.10.3".
Older SDK versions don’t include the SDK version in their mDNS TXT records. As a result, the client defaulted to its own SDK version when displaying device info. This has been fixed by explicitly setting sdkVersion to "<3.10.3" when the version is missing.
> Fix Incorrect SDK Version Display for Devices with SDK <3.10.3

- core/corecontainers/src/dictobject_impl.cpp
- core/corecontainers/src/listobject_impl.cpp
- core/coretypes/include/coretypes/common.h
- core/coretypes/src/util.cpp
- core/coretypes/tests/test_intfid.cpp
Change the signature of `daqStringToInterfaceId` to be C-compatible. Optimize it by rewriting it without using regex.
The current implementation uses std::string as a parameter, which is not C-compliant. The updated signature uses a standard C-style string.
Reimplements the conversion without regex, which is slower than the new implementation.
```diff
- ErrCode daqStringToInterfaceId(std::string& guidStr, daq::IntfID& iid);
+ErrCode daqStringToInterfaceId(daq::ConstCharPtr guidStr, daq::IntfID& iid);
```
(Changes required in openDAQ applications/executables)
- (E.g. change renamed function name)
- ...
Instead of:
```cpp
std::string guidStr = "....";
daq::IntfID id;
daqStringToInterfaceId(guidStr, id);
```
Do:
```cpp
std::string guidStr = "....";
daq::IntfID id; …
```
> Change daqStringToInterfaceId signature to C compatible, rewrite it without regex for optimization

- core/opendaq/component/include/opendaq/component_impl.h
- shared/libraries/config_protocol/src/config_protocol_server.cpp
Optimize `IComponent.findComponent`
`findComponent` uses  `getItem` and `hasItem` methods of `IComponent`. The former already returns an error if the item is not found, so there is no need to call `hasItem`. Note that both methods employ a recursive lock, which means that the optimization reduces the number of recursive locks by 50%.
> Optimize find component

- bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/OpenDAQ_CITests.cs
- bindings/dotnet/openDAQ.Net/openDAQ.Net/core/coretypes/BaseObject.cs
Fixed AccessViolation on Garbage Collection.
When Garbage Collector destroys managed instance object before managed child objects (OPC UA connection), destruction of the child objects leads to a native AccesViolationException that cannot be caught in .NET.
With the instance the `ModuleManager` will also be destroyed, unloading the module libraries, rendering those child objects invalid.
This fix (lines 657+) uses `GC.ReRegisterForFinalize(this)` when the managed instance object is about to be released (`ReleaseReference()`) in the common `Dispose()` method. That way, the finalization of the instance is put at the end of the queue so that references to child objects are kept alive for finalization.
Edit: The CI tests had to be adapted, since the instance disposal is now delayed, so using a …
> [TBBAS-2183/SHS-152] .NET Bindings - Fixed AccessViolation on Garbage Collection

- bindings/python/core_objects/include/py_core_objects/py_variant_extractor.h
- bindings/python/core_types/include/py_core_types/py_opendaq_daq.h
- bindings/python/core_types/src/py_base_object.cpp
- bindings/python/opendaq/include/py_opendaq/py_packet_buffer.h
- bindings/python/opendaq/py_opendaq.cpp
- bindings/python/tests/test_core_types.py
Internal changes required for the Python device & function block module
These changes are necessary for implementing the Python module. 
Requires an additional fix for the stream reader not overwriting the notification method on the input port, which will be addressed in the multi-reader PR.
> openDAQ and python bindings updates for python module

- changelog/changelog_3.10-3.20.md
- modules/tests/test_opendaq_device_modules/test_opcua_device_modules.cpp
- shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_component_impl.cpp
- shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_property_object_impl.cpp
- shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/objects/tms_server_component.h
Ensure that `ComponentConfig` is not exposed as a property of components in OPC UA.
`ComponentConfig` is an internal property of the `Component` object, represented by a `PropertyObject` type, which stores the configuration used during the component's creation. Due to an oversight, this internal property was inadvertently exposed to OPC UA clients as a regular component property.
This PR corrects that behavior by excluding `componentConfig` from the set of properties exposed via OPC UA, keeping it internal as originally intended.
None
None
None
> Exclude ComponentConfig from OPC UA Component Properties

- changelog/changelog_3.20-3.30.md
- core/coreobjects/include/coreobjects/eval_nodes.h
- shared/libraries/config_protocol/include/config_protocol/config_client_device_impl.h
- shared/libraries/opcuatms/opcuatms_client/src/objects/tms_client_device_impl.cpp
Do not throw an exception when getting operation modes on old devices. Return default state instead.
> Gracefully handle operation mode getters when not supported on server

- changelog/changelog_3.20-3.30.md
- core/opendaq/signal/include/opendaq/bulk_data_packet.h
- core/opendaq/signal/include/opendaq/bulk_data_packet_factory.h
- core/opendaq/signal/include/opendaq/data_packet_impl.h
- core/opendaq/signal/include/opendaq/generic_data_packet_impl.h
- core/opendaq/signal/src/CMakeLists.txt
- core/opendaq/signal/src/bulk_data_packet.cpp
- core/opendaq/signal/tests/CMakeLists.txt
- core/opendaq/signal/tests/test_bulk_data_packet.cpp
Adds functions to create multiple packets with one heap allocation
The typical value signal and the domain signal require four heap allocations per packet pair. `daqBulkCreateDataPackets` creates multiple packets for multiple signals with one heap allocation. The heap memory deallocation occurs when all of the packets' reference counts drop to zero.
The `daqBulkCreateDataPackets` does not include a smart pointer wrapper because we usually want to avoid list and vector allocations. However, two helper wrappers exist when creating a value/domain packet pair for one signal.
In terminal use:
```cpp
size_t sampleCount = 4;
Int offset = 100;
size_t align = 1;
const auto valuePacket = daq::DataPacketWithImplicitDomainPacket(valueDescriptor, domainDescriptor, sampleCount, offset, align);
const …
```
> Bulk create data packets

- changelog/changelog_3.10-3.20.md
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/streaming_manager.h
- shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
- shared/libraries/native_streaming_protocol/src/native_streaming_server_handler.cpp
- shared/libraries/native_streaming_protocol/src/streaming_manager.cpp
Fixes race conditions during signal removal that caused exceptions on the server and client side of the native streaming protocol implementation.
A race condition was occurring during the signal removal processing sequence due to issues in parallel handling, leading to exceptions on either the server or client side. 
The sequence that led to issues was as follows:
* A parent component is removed.
* A core event is triggered to reflect the removal.
* The config server catches the core event and propagates it to the client.
* The streaming server catches the same core event and:
- Unregisters the signal within the streaming manager.
- Removes the reader if the signal was subscribed - this action is synchronized with the signals' data accumulation phase in the streaming read thread.
- …
> Fix race condition in native streaming caused by signal removal

- core/opendaq/signal/include/opendaq/data_packet_impl.h
- core/opendaq/signal/include/opendaq/wrapped_data_packet.h
- core/opendaq/signal/include/opendaq/wrapped_data_packet_factory.h
- core/opendaq/signal/include/opendaq/wrapped_data_packet_impl.h
- core/opendaq/signal/src/CMakeLists.txt
- core/opendaq/signal/src/wrapped_data_packet_impl.cpp
- core/opendaq/signal/tests/CMakeLists.txt
- core/opendaq/signal/tests/test_wrapped_data_packet.cpp
Wrapped data packets
Wrapped data packets are packets that wrap another data packet as a source and use their data buffers. A wrapped data packet can set a different data descriptor from the source. This is useful if a function block processes source packets in a way that leaves raw data untouched, and it only changes post-scaling factors. This avoids unnecessary memory copies of raw data.
Note that the current implementation of native and LT streaming does not recognize wrapped data packets and treats them as standard data packets. This means that if both source and wrapped data packets are transmitted, the underlying shared buffer will be transmitted twice. This represents a potential area for future optimization.
In C++ use:
```cpp
const auto domainDescriptor = DataDescriptorBuilder() …
```
> Wrapped data packet

- bindings/python/core_objects/generated/py_argument_info.cpp
- changelog/changelog_3.20-3.30.md
- core/coreobjects/include/coreobjects/argument_info.h
- core/coreobjects/include/coreobjects/argument_info_factory.h
- core/coreobjects/include/coreobjects/argument_info_impl.h
- core/coreobjects/src/argument_info_impl.cpp
- core/coreobjects/tests/test_argument_info.cpp
- core/coreobjects/tests/test_property_object.cpp
- modules/ref_device_module/src/ref_device_impl.cpp
- shared/libraries/config_protocol/tests/test_nested_property_objects.cpp
- shared/libraries/opcuatms/opcuatms/src/converters/argument_converter.cpp
- shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/objects/tms_server_component.h
- shared/libraries/opcuatms/opcuatms_server/include/opcuatms_server/objects/tms_server_object.h
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_object.cpp
- shared/libraries/opcuatms/opcuatms_server/src/objects/tms_server_property_object.cpp
- shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_property_object.cpp
When publishing Procedure or Function-type properties it was not possible to define what kinds of elements are expected in list and dictionary function arguments. This PR implements the option to add such info.
`IArgumentInfo` can now be constructed with a list of `IArgumentInfo` objects as a factory parameter. The Argument Info types in said list denote the expected parameter types of procedures/functions that accept `ctList` type arguments. The names of said Argument Info objects in the list denote the keys of `ctDict` type arguments.
NOTE: This does not work over OPC UA as list and dict-type arguments are not supported there (and were not supported up until now either).
```diff
+ [function] IArgumentInfo::getItemType(CoreType* itemType)
+ [function] IArgumentInfo::getKeyType(CoreType* …
```
> Add support for list and dictionary item/key type identification in Argument Info

- modules/native_streaming_client_module/include/native_streaming_client_module/native_device_impl.h
- modules/native_streaming_client_module/src/native_device_impl.cpp
- shared/libraries/config_protocol/src/config_protocol_client.cpp
Fixes the stability within the native device removal and disposal processes
- Keeps the strong reference to the top parent device (i.e. the mirrored copy of root device) until last incoming core event notification of RPC reply handled
- Males disconnect and cleanup procedure called explicitly in native device destructor
- Adds graceful handling of failures with sending the config protocol no-reply commands
> Fix and stabilize native device removal and disposal flow 3.10

- changelog/changelog_3.20-3.30.md
- core/coreobjects/src/CMakeLists.txt
Fixes missing `property_metadata_read_args` smart pointer header installation
> Fix missing property args header installation

- core/opendaq/signal/src/CMakeLists.txt
This PR fixes compile errors when including `<signal_impl.h>` (directly or indirectly) when using an installed (not built-in-tree) version of openDAQ.
`signal_impl.h`, which is public, has been modified to reference `data_packet_impl.h`. The latter is currently private and also references many additional private headers. All of these headers must therefore become public and be installed to avoid compile errors. Alternatively, `signal_impl.h` could be refactored to not reference `data_packet_impl.h`, but this seems nontrivial.
None.
> Install missing headers ref'd from signal_impl.h

- modules/new_websocket_streaming_server_module/src/websocket_server.cpp
Fix the new WebSocket Streaming server so that it accepts IPv6 as well as IPv4 connections.
This change adjusts the Boost.Asio TCP acceptors so that they listen on both IPv4 and IPv6 ports.
Previously only IPv4 was supported. This is because passing a default-constructed `ip::address` object implicitly binds to IPv4 (unlike the BSD socket API). Instead we have to pass in a `v6()` protocol object and then attempt to ensure the IPv6-only socket option, if supported, is off (this option appears not to be supported on default Boost installations, which is fine).
None, the change is transparent and does not change the API or ABI.
None.
> new_websocket_streaming_server_module: support IPv6

- bindings/dotnet/openDAQ.Net/openDAQ.Net.CI.Test/OpenDAQ_CITests.cs
- bindings/dotnet/openDAQ.Net/openDAQ.Net.Test/OpenDaqExplanationsTests.cs
- docs/Antora/modules/explanations/pages/multireader_spec.adoc
- docs/Antora/modules/explanations/pages/property_system.adoc
- docs/Antora/modules/explanations/pages/readers.adoc
C# example additions to `readers.adoc` and `multireaders_spec.adoc`.
In this PR you find the C# additions to `readers.adoc` and `multireaders_spec.adoc`.
Some examples were skipped though always a comment has been added.
Additions:
1. Added (local) function `GetSampleRate()` as substitute to C++ helper function `reader::getSampleRate()` which never gets RTGened. Perhaps it should just be implemented directly in the MultiReader as `getSampleRateHelper(DataDescriptor descriptor)`.
2. Substituted C++ code `std::lcm` by a fictive function `GetLeastCommonMultiple()` and added a comment to a stackoverflow answer with a nice example.  
Of course, when this is unwanted, the comment has to be changed to "please implement function yourself".
3. Not done examples where it is impossible to translate …
> [TBBAS-2107] .NET Bindings - Supplement, improve or add C# examples in the documentation

- bindings/python/package/build_pip.py
- bindings/python/package/opendaq/__init__.py
- examples/applications/python/GUI Application/gui_demo.py
Add support for `-v`/`--version` and `__version__` to the python package.
- From the command line, you can now use `pip -m opendaq --version` to write out the package location followed by the openDAQ version.
- From the interpreter, you can access the version with `import opendaq; opendaq.__version__`
> Add support for --version and __version__ to python package

- bindings/python/opendaq/generated/device/py_device.cpp
revert `py_device.cpp`: removed `operation_mode` getter returned backed 
**None**
**None**
**None**
**None**
**None**
> Revert py_device.cpp: operation_mode getter

- core/coreobjects/src/CMakeLists.txt
- core/opendaq/opendaq/src/CMakeLists.txt
Make `mutex_impl.h` and `module_authenticator_impl.h` a part of the installation.
I've tested this by creating and using the Windows installer locally and it appears to fix the issue.
> Fix installation (`mutex_impl.h` and `module_authenticator_impl.h`)

- examples/applications/python/GUI Application/gui_demo.py
gui_demo.py was changed to use __version__ for returning the openDAQ version string; but if you are running it manually and are using an old openDAQ package that doesn't support __version__, this will crash on startup.
> Stop crashing gui_demo on startup when executing manually with old openDAQ package

- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- tests/integration/test_opendaq_device_modules/test_native_device_modules.cpp
Do not send client config on reconnect if the device is locked.
If the "RestoreClientConfigOnReconnect" option is used and the client reconnects to a locked device, the device will not accept the reconnect request because it will fail on the `update` RPC. This PR ignores the option and forces the device to update the client instead when the device is locked.
> Do not send client config on reconnect if device is locked

- .github/workflows/ci.yml
- CMakeBasePresets.json
- CMakeLists.txt
- changelog/changelog_3.20-3.30.md
- core/corecontainers/src/listobject_impl.cpp
- core/coreobjects/include/coreobjects/property_impl.h
- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coretypes/include/coretypes/intfs.h
- core/coretypes/tests/test_json_deserializer.cpp
- core/opendaq/reader/src/signal_reader.cpp
- examples/modules/audio_device_module/tests/test_fb_wav_reader.cpp
- examples/modules/ref_device_module/include/ref_device_module/ref_can_channel_impl.h
- examples/modules/ref_device_module/include/ref_device_module/ref_channel_impl.h
- examples/modules/ref_device_module/src/ref_can_channel_impl.cpp
- examples/modules/ref_fb_module/include/ref_fb_module/power_reader_fb_impl.h
- examples/modules/ref_fb_module/include/ref_fb_module/renderer_fb_impl.h
- examples/modules/ref_fb_module/src/renderer_fb_impl.cpp
- external/CMakeLists.txt
- external/taskflow/CMakeLists.txt
- external/taskflow/patches/0004-IntelLLVM-Support.patch
- modules/native_streaming_client_module/src/native_streaming_client_module_impl.cpp
- shared/libraries/config_protocol/include/config_protocol/config_client_property_object_impl.h
- shared/libraries/opcuatms/tests/opcuatms_integration/test_tms_integration.cpp
- shared/libraries/packet_streaming/src/packet_streaming_client.cpp
- shared/libraries/websocket_streaming/src/streaming_server.cpp
Enable building openDAQ with the Intel oneAPI LLVM compiler
- Patch TaskFlow to resolve issues with Intel-LLVM compiler detection  
- Add CMake build presets for Intel-LLVM compiler  
- Provide necessary build flags for Intel oneAPI LLVM compiler  
- Remove unused class members in reference modules and address other warnings  
- Fix `cxxabi.h` include errors  
- Introduce Ubuntu and Windows CI jobs for Intel-LLVM compiler — verified as passing, then disabled
- `test_core_types` fails on Ubuntu 22.04 in `TEST_F(JsonDeserializerTest, floatMin)` during float minimum deserialization. This is possibly caused by a bug in the Intel math runtime library. However, the same test passes locally on Ubuntu 20.04.
> Add support for Intel-LLVM compiler

- core/opendaq/modulemanager/src/module_manager_impl.cpp
- core/opendaq/modulemanager/tests/module_manager_test.cpp
Fixed relative path search in ModuleManagerImpl::GetModulesPath.
Changed one module manager test to match new result.
> fixed module manager relative path module search

- changelog/changelog_3.20-3.30.md
- modules/native_streaming_client_module/src/native_device_impl.cpp
- shared/libraries/config_protocol/include/config_protocol/config_protocol_client.h
- shared/libraries/config_protocol/include/config_protocol/config_protocol_streaming_producer.h
- shared/libraries/native_streaming_protocol/include/native_streaming_protocol/native_streaming_client_handler.h
- shared/libraries/native_streaming_protocol/src/native_streaming_client_handler.cpp
- shared/libraries/packet_streaming/include/packet_streaming/packet_streaming_server.h
- shared/libraries/packet_streaming/src/packet_streaming_server.cpp
Fixes a crash in device applications based on SDK v3.10 that occurred when client-to-device streaming is running and the config protocol version number in use is lower than 10.
- Enables downgrading the JSON serializer version in the packet streaming server used for client-to-device streaming.
> Fix compatibility issue with 3.10 in C2D-streaming

- core/opendaq/modulemanager/src/module_manager_impl.cpp
Added protected set property value call.
`setPropertyValueInternal` throws `ACCESS_DENIED` when trying to change `ctObjects` so I added a protected call as per Nikolai's suggestion.
> added protected setter for ctObjects when overriding config properties

- core/opendaq/device/include/opendaq/device_impl.h
Convert `IComponent` to `IServer` for `getServers` call
None
None
None
> [TBBAS-2623] Fix: Python: `instance.servers` returns list of `IComponent` instead of `IServer`

- core/coreobjects/include/coreobjects/property_object_impl.h
- core/coreobjects/src/permission_manager_impl.cpp
- core/coretypes/include/coretypes/intfs.h
- core/coretypes/src/intfs.cpp
Replace static `Permissions` object to factory function to get rid of memory leak 
None
None
```diff
+ extern "C" PUBLIC_EXPORT void daqDisableObjectTracking();
+ extern "C" PUBLIC_EXPORT void daqEnableObjectTracking();
```
None
> Bugfix: Permissions memleak

- core/opendaq/device/include/opendaq/device_impl.h
- core/opendaq/opendaq/src/instance_builder_impl.cpp
- core/opendaq/opendaq/src/instance_impl.cpp
- core/opendaq/utility/include/opendaq/option_helpers.h
- core/opendaq/utility/src/CMakeLists.txt
Add an option to set pretty print for the `saveConfiguration` call. Save device configuration with `forUpdate` option.
The `saveConfiguration` method always uses pretty print. This PR adds an option to switch this off. The preferred method would be to pass this option as a method parameter, but this would break the API. As a workaround, this behaviour can be set through context options.
This PR also fixes issue SHS-233.
In C++ use:
```cpp
builder.getOptions().get("Configuration").asPtrOrNull<IDict, DictPtr<IString, IBaseObject>>(true).set("SerializePrettyPrint", False);
```
> Add option to set configuration serialization pretty print
